### ISSUE TITLE
JVM support

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1]
This could be a built-in and pprof-integrated version of [perf-map-agent](https://github.com/jvm-profiling-tools/perf-map-agent) and/or [async-profiler](https://github.com/jvm-profiling-tools/async-profiler).

### Plan
1. In Phase one, use `async-profiler` to profile JVM processes. **https://github.com/parca-dev/parca-agent/issues/1115**
2. In Phase two, use the eBPF profiler to collect the profiles.

**Comment by cskinfill** [comment]
any progress with JVM support?

**Comment by brancz** [comment]
Starting with the [`v0.3.0`](https://github.com/parca-dev/parca-agent/releases/tag/v0.3.0) release if the perf-map agent is used, then JVM can be profiled with parca-agent today!

**Comment by brancz** [comment]
Looks like there is also some precedence of profilers at the intersection of eBPF and java, that some inspiration could come from: https://github.com/weixingsun/jBProF

**Comment by petr-postulka** [comment]
Hi, is there any update for this ticket? Any ETA when JVM profiling is supported by parca-agent by default?

**Comment by kakkoyun** [comment]
We just started working on this. We plan to land an initial support before this year ends.

**Comment by Hixon10** [comment]
FYI: Maybe [https://github.com/grafana/JPProf](https://github.com/grafana/JPProf) helps somehow with implementation for given task.

**Comment by kakkoyun** [comment]
> FYI: Maybe https://github.com/grafana/JPProf helps somehow with implementation for given task.

Thanks for the suggestion. `JPProf` is a library you need to add to your application, so it's instrumentation. We are planning to provide an experience where you don't need to change anything in your application :)

**Comment by fzyzcjy** [comment]
Hi, is there any updates (after two years)? This project looks quite interesting, and I hope to use it in my environment!

**Comment by brancz** [comment]
We’re making progress and a first integrated version should be only a few weeks away.

Just to be clear though, you have always been able to profile Java workloads by enabling these flags: https://github.com/parca-dev/parca-demo/blob/882b4e77496507ec4b0b839df5dd15c6beff8dd2/java/Dockerfile#L19

**Comment by gnurizen** [comment]
New agent supports JVM w/o any instrumentation necessary.
