### ISSUE TITLE
Automate updating debian snapshots

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#10]
```
E: Release file for http://snapshot.debian.org/archive/debian-security/20210621T000000Z/dists/buster/updates/InRelease is expired (invalid since 30d 18h 29min 0s). Updates for this repository will not be applied.
E: Release file for http://snapshot.debian.org/archive/debian/20210621T000000Z/dists/buster-updates/InRelease is expired (invalid since 30d 18h 32min 9s). Updates for this repository will not be applied.
E: Release file for http://snapshot.debian.org/archive/debian/20210621T000000Z/dists/buster-backports/InRelease is expired (invalid since 30d 18h 32min 10s). Updates for this repository will not be applied.
STEP 4: FROM docker.io/debian@sha256:c6e92d5b7730fdfc2753c4cce68c90d6c86a6a3391955549f9fe8ad6ce619ce0 AS all
error building at STEP "RUN apt-get update && apt-get install -y clang-11 make gcc coreutils elfutils binutils zlib1g-dev libelf-dev ca-certificates netbase &&         ln -s /usr/bin/clang-11 /usr/bin/clang &&         ln -s /usr/bin/llc-11 /usr/bin/llc": error while running runtime: exit status 100
Trying to pull docker.io/library/debian@sha256:c6e92d5b7730fdfc2753c4cce68c90d6c86a6a3391955549f9fe8ad6ce619ce0...
time="2021-07-28T14:41:21Z" level=error msg="exit status 100"
make: *** [Makefile:182: container] Error 100
Error: Process completed with exit code 2.
```

For now, we just disabled checks:
https://snapshot.debian.org/
> To access snapshots of suites using Valid-Until that are older than a dozen days, it is necessary to ignore the Valid-Until header within Release files, in order to prevent apt from disregarding snapshot entries ("Release file expired"). Use aptitude -o Acquire::Check-Valid-Until=false update or apt-get -o Acquire::Check-Valid-Until=false update for this purpose.

**Comment by kakkoyun** [comment]
Check if this could be handled using Renovate.

(Lazily pinging you) @maxbrunet any ideas?

**Comment by kakkoyun** [comment]
> Yes! I have in mind to create a feature request for a `date` datasource, if they like the idea, I might implement it myself (contributing is easy)

Awesome :+1: I'll give attention to Renovate soon.

> It would also be useful for updating the Rust nightly release, unless you plan to update to the next stable?

We need to check which version our changes going to end up. Any ideas @v-thakkar?

**Comment by v-thakkar** [comment]
Which changes do you mean @kakkoyun ? If you meant llvm-sys ones then it is not part of Rust nightly so we'll just pin the new version of llvm-sys in bpf-linker and Aya.

We can't use Rust stable yet because the bpf-architecture target is not available in stable. (I don't know when that will be, just asked in Aya's discord as I couldn't find any GH issue to track that). So we should automate pinning the Rust nightly release until then. The only important thing to check for picking the rust nightly is that nothing is broken here for both x86 and arm64 here: https://rust-lang.github.io/rustup-components-history/

**Comment by maxbrunet** [comment]
Debian snapshots happens at random times: https://snapshot.debian.org/archive/debian/?year=2022&month=6

A date datasource would not be able to help, we would need a dedicated datasource to get the list of snapshots

**Comment by kakkoyun** [comment]
This is not needed anymore. We will be using https://github.com/parca-dev/cross-builder for consistent cross-builds.
