### ISSUE TITLE
Wrong frames in profile

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1025]
Not sure if this is an issue only happening to the dwarf-based unwinder. It used to work fine (https://github.com/parca-dev/parca-agent/commit/0abd8e737e1f931ea3990953643577ef4208096a) but now it's broken.

This might be an issue in the unwinder, profile generation, or backend. Needs more investigation

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/959128/202024001-8966552c-2ee8-41ad-91b8-ce361d933ace.png">

cc @kakkoyun

**Comment by javierhonduco** [comment]
I think this is a Parca issue because that same revision shows the broken stacks now

**Comment by brancz** [comment]
Which version of parca was this using?

**Comment by javierhonduco** [comment]
Unfortunately, I don't remember, but I think it was a bit old. Tried on this revision and it was all good, so closing this issue :)

```
commit 6dfde342f6a489f34c91c92130ee6ed414bd0bb6 (HEAD -> main)
Author: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Date:   Sun Nov 13 20:00:47 2022 +0000

    chore(deps): update quay.io/containers/podman docker tag to v4.3.0 (#2098)
    
    Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>

```
