### ISSUE TITLE
ci: Snap builds fail on tags

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1027]
https://github.com/parca-dev/parca-agent/actions/runs/3474268375/jobs/5807311290#step:5:17

@jnsgruk any quick ideas come to mind?

**Comment by jnsgruk** [comment]
Oops. Think the PR mention above should sort it!

**Comment by kakkoyun** [comment]
@jnsgruk Thanks for swift action ❤️

**Comment by kakkoyun** [comment]
I realized we hadn't closed this one correctly. But I'll reuse this. The snap build failed for the latest release https://github.com/parca-dev/parca-agent/actions/runs/3532617184/jobs/5927288986

We can fix it going forward and release it manually this time.

cc @jnsgruk

**Comment by kakkoyun** [comment]
> @kakkoyun do you want me to do the manual release or will you?

Please go for it. Thanks 🙏

**Comment by jnsgruk** [comment]
Okay, that's done:

![image](https://user-images.githubusercontent.com/668505/203589186-dea020a6-7c91-4d05-8732-c008f828af0b.png)

I'll leave it to you to decide when the release is ready for `latest/stable` - feel free to ping me if you'd like me to promote it.

**Comment by kakkoyun** [comment]
We officially released `v0.10.0`. We can promote it. If we discover any issues, we will release a patch version. Let's promote.
