### ISSUE TITLE
relabel_configs not working in v0.10.0-rc.0

### ISSUE THREAD

**Issue by rafaeljesus** [parca-dev/parca-agent#1057]
Hi everybody, I've recently upgraded parca-agent to `v0.10.0-rc.0`,
and in this version the `--pod-label-selector` was removed in favor of using the _relabel_configs_ from prometheus,

However, I cannot filter out pods, the agent is scraping all pods from the cluster, even though the _relabel_configs_ is configured to _keep_ profiles with label=`namespace=staging-space-station` and drop all the rest (did I get this right?)

Here is the agent config `parca.yaml`:

```yaml
apiVersion: v1
data:
  parca.yaml: |-
    relabel_configs:
    - source_labels: [namespace]
      regex: staging-space-station
      action: keep
kind: ConfigMap
...
```

and here is a profile that should have been dropped:

![Screenshot 2022-11-22 at 14 47 05](https://user-images.githubusercontent.com/1216425/203330915-0958d2f8-221b-4c98-94d4-06d1c694f6c2.png)

I guess because of this, the server is being overloaded very quickly, I am trying to issue queries in the UI but I can't actually render any results, I see the following error at any sample I click:

`An error occurred: could not find profile at requested time and selectors`

![Screenshot 2022-11-22 at 14 42 45](https://user-images.githubusercontent.com/1216425/203328870-781c641b-506a-41af-87c3-3f7b476b62ee.png)

The resource utilization in the server pod during OOMs:
```
  ~ k top pod staging-parca-5b5788998b-vzqxt
NAME                             CPU(cores)   MEMORY(bytes)
staging-parca-5b5788998b-vzqxt   10456m       36107Mi
```

- The server requests/limits:
  -  12 CPU / 36 GB Memory
- agent version: v0.10.0-rc.0
- server version: v0.14.0 (also tasted with v0.13.0 and the same behavior applies)

I'd appreciate any help, thanks in advance

**Comment by maxbrunet** [comment]
Hi @rafaeljesus, the agent will look for `parca-agent.yaml` by default, have you set `--config-path`?

The selected processes and the loaded config can also be previewed in the agent UI on port 7071, how does it look there?

**Comment by rafaeljesus** [comment]
> 

hey Max, yes did set but with the pointing to the wrong path 🙈 

let me fix it and will get back here asap

**Comment by rafaeljesus** [comment]
> should I open another issue for this?

done https://github.com/parca-dev/parca-agent/issues/1060

**Comment by kakkoyun** [comment]
> the agent now finds and filters out the pods just right,

So is this issue fixed? @rafaeljesus

**Comment by rafaeljesus** [comment]
this issue (i.e., relabel_confgs) is fixed, thanks everybody
