### ISSUE TITLE
could not tran addreess of .so file

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca-agent#1098]
file with .so suffix could not transform:
```
/proc/722978/root/usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so
```

#### perf script
perf script could successfully tran address to funcname.
```
AliYunDun 722978 8431771.617441:     250000 cpu-clock:
        ffffffffb58dec35 mutex_lock+0x15 ([kernel.kallsyms])
        ffffffffb52d672d __fdget_pos+0x3d ([kernel.kallsyms])
        ffffffffb52b7faa ksys_read+0x1a ([kernel.kallsyms])
        ffffffffb5003e4b do_syscall_64+0x5b ([kernel.kallsyms])
        ffffffffb5a00085 entry_SYSCALL_64_after_hwframe+0x44 ([kernel.kallsyms])
            7fdecc6fd75d [unknown] (/usr/lib64/libpthread-2.17.so)
            7fdec85fcc49 CKprobeEventMgr::run+0x235 (/usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so)
            7fdece61c11a aqs::CThreadUtil::ThreadFunc+0x1ba (/usr/local/aegis/aegis_client/aegis_11_37/libaqsUtil.so.1)
```
#### addr2line
base address:
```
cat /proc/722978/maps | grep usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so
7fdec83c1000-7fdec8687000 r-xp 00000000 fd:01 1315302                    /usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so
```

use addr2line to tran address 0x7fdec85fcc49 - 0x7fdec83c1000 = 0x23bc49
```
[root@iZuf61mwgz5hr4jha4g1r3Z ~]# addr2line -aif --demangle -e  /proc/722978/root/usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so
23bc49
0x000000000023bc49
CKprobeEventMgr::run()
??:?
```

#### what i expect
parca-agent could tran address to funcname just like addr2line and perf.

#### addr2line.Symbols
use addr2line.Symbols to parse file.

error:
```
 msg="failed to create go liner" filename=/proc/722288/root/usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
```

**Comment by zdyj3170101136** [comment]
i find the reason is this commit removed dynamic symbol:
https://github.com/parca-dev/parca/commit/2b67154d490d9565d77ad4f11783f60045f46dca#diff-08e8e7603c3b4173998f7a1eed15fb31b4a425b452b52a6a70d939979b60d519

**Comment by kakkoyun** [comment]
> i find the reason is this commit removed dynamic symbol: [parca-dev/parca@2b67154#diff-08e8e7603c3b4173998f7a1eed15fb31b4a425b452b52a6a70d939979b60d519](https://github.com/parca-dev/parca/commit/2b67154d490d9565d77ad4f11783f60045f46dca#diff-08e8e7603c3b4173998f7a1eed15fb31b4a425b452b52a6a70d939979b60d519)

We have an issue for this https://github.com/parca-dev/parca/issues/2056
Contributions are welcome as always 🤗

**Comment by zdyj3170101136** [comment]
> KprobeEventMgr

the function name is both in .symtab and .dynsym:
```
[root@iZuf61mwgz5hr4jha4g1r3Z ~]# readelf --symbols /usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so | grep CKprobeEventMgr3runE
  8938: 000000000023ba14  1703 FUNC    GLOBAL DEFAULT   10 _ZN15CKprobeEventMgr3runE
[root@iZuf61mwgz5hr4jha4g1r3Z ~]# readelf --dyn-syms /usr/local/aegis/aegis_client/aegis_11_37/libModuleMetadata.so | grep CKprobeEventMgr3runE  8938: 000000000023ba14  1703 FUNC    GLOBAL DEFAULT   10 _ZN15CKprobeEventMgr3runE
```

do not know why it could not resolve?

**Comment by kakkoyun** [comment]
@zdyj3170101136 Does https://github.com/parca-dev/parca/pull/2491 fixes this issue?
