### ISSUE TITLE
Cache `hash.File` result

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1100]
About ~5% of CPU time of Parca Agent are spent in hashing object files to prepare for the debuginfo `Exists` gRPC call. This is even though files are extremely unlikely to change. I think we should only rehash if the `mtime` of the file changes. Yes, it's possible to modify the `mtime`, but that would mean that a user is shooting themselves in the foot by doing so, so I think that tradeoff is worth it.

**Comment by javierhonduco** [comment]
Ah! Great timing :D Was thinking about this yesterday for a similar problem we are going to face for the DWARF unwinder. The current line of thought I have is to use the `inode` of the file. It should be unique per FS and machine in Linux. So we could maybe use this in the Agent to avoid the rehashing here?

Was going to use this for the unwinder, but I think that here it could be slightly better than the `mtime` in case there are clock drifts or as you say if it gets modified by users or some other problem

**Comment by maxbrunet** [comment]
`inode` does not seem robust to me, it does not change if the file is modified and if a file is deleted, the next created could re-use the `inode`

**Comment by javierhonduco** [comment]
Oh, you are right! Thanks for bringing this up. I think I got this wrong because btrfs, the filesystems I use, does not recycle them, but this is an implementation detail for each filesystem!

**Comment by kakkoyun** [comment]
I think we have a caching mechanism now
https://github.com/parca-dev/parca-agent/blob/ba2df5bc9b97b6434a5509dfa586cbbadf7d8cc3/pkg/debuginfo/manager.go#L321-L356

I am closing this. Please don't hesitate to re-open it if it doesn't what you expected.
