### ISSUE TITLE
process which do not have /proc/pid

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca-agent#1103]
when i run parca-agent in k8s, i encounter some process do not have   /proc/pid.

process name: runc
pid: 153938

cmd:
```shell
[root@iZuf61mwgz5hr4jha4g1r3Z perfdump]# cd /proc/153874
-bash: cd: /proc/153874: No such file or directory
```

but if you use perf record, it will get perfRecordMapping of this process.
mapping file name(only one file): 
/usr/lib64/libc-2.17.so

**Comment by kakkoyun** [comment]
@zdyj3170101136 This could happen if the process is short-lived. When we try to read the mapping, the process might have already gone. @javierhonduco and I are bouncing off some ideas to improve this already.

**Comment by kakkoyun** [comment]
We hope to address these issue as part of #697
