### ISSUE TITLE
Embed "async-profiler" to profile JVM processes

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1115]
Currently, in parca-agent we’re using [perf-map-agent](https://github.com/parca-dev/perf-map-agent) and attach it at the runtime for profiling JAVA applications. To keep staying true to our zero instrumentation policy, we want to profile java applications without the need for an external agent or instrumentation of any kind. To avoid reinventing the wheel, we will start with embedding [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) in the parca-agent.

The work will be done in multiple phases. In the V1 of the implementation, we'll be using most of the components from the async profiler as it is. Checkout our [public RFC](https://docs.google.com/document/d/1_a3kW9N7mkVGXl2MScYQvldr-OY5y3QQfXHYgyHVUUw/edit#heading=h.ajdd04yoeml7) for more details on the plan. **[Note: some details might be outdated]**

TODOs for V1:
- [x] Discover Java processes via hsperfdata
- [x] Add metadata label for the java processes
- [x] ~~Add Go package to interact with C++ code~~ (Not required anymore)
- [x] #1510 
- [ ] #1508 
- [x] Add JFR to PProf package #1499

**Comment by fabxc** [comment]
Will this mean mixed stacks will be supported in v1 as well since async-profiler supports them? If yes, then in the same [modes](https://github.com/jvm-profiling-tools/async-profiler/blob/master/profiler.sh#L44) it supports as well or will C stacks go through the agent's existing logic.

**Comment by v-thakkar** [comment]
@fabxc In the first version, it'll be handled in the same modes as async profiler does at the moment. But eventually, we do plan to use the agent's existing logic by collaborating with async profiler maintainers. I need to update the internal RFC but will add it here in next few days: https://drive.google.com/drive/folders/1qbsh7Fa5mx8p97QLZ9LELKC45HcYSanT

**Comment by fzyzcjy** [comment]
Hi, is there any updates? Thanks!
