### ISSUE TITLE
local-test: Add a Vagrantfile

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1130]
Add Vagrantfile for ease of test

e.g https://github.com/aquasecurity/tracee/blob/41a0761776a5c735c3ae9a2c33a3812fc2e4a90a/Vagrantfile

**Comment by javierhonduco** [comment]
I don't dislike the idea in principle but vagrant seems to be abandonware at this point. It's not well supported on Apple Silicon either. Perhaps we could provide a great developer experience with a more modern and maintained set of tools?

**Comment by kakkoyun** [comment]
> I don't dislike the idea in principle but vagrant seems to be abandonware at this point. It's not well supported on Apple Silicon either. Perhaps we could provide a great developer experience with a more modern and maintained set of tools?

💯 I couldn't agree more. I've other plans.
