### ISSUE TITLE
arm64 release artifact name should be aarch64 not arm64

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1211]
It would be nice to be able to write a command such as 

```
curl -sL https://github.com/parca-dev/parca-agent/releases/download/v0.11.0/parca-agent_0.11.0_`uname -s`_`uname -m`.tar.gz
```

For tutorials using Parca Agent, however, `uname -m` on arm64 returns `aarch64`, but the artifact is called `arm64`. We already fixed this for [amd64, which returns `x86_64`](https://github.com/parca-dev/parca-agent/blob/508358a3adf6380fcffbfa8e5a35806b135d3440/.goreleaser.yml#L82), but not for arm64.

**Comment by kakkoyun** [comment]
I think `uname -m` has different outputs on Linux and Darwin. And `arm64` is the output for Darwin. We should only support Linux.
