### ISSUE TITLE
Make profiling frequency configurable and use prime number

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1212]
I propose a new flag `--cpu-sampling-frequency` to configure the frequency at which profiling data is collected. Additionally, I propose we change the currently hardcoded default of 100 to 19. 19 because it is a prime number, and primes are good to avoid collisions with other things that may be happening periodically on a machine. In particular, 100 samples per second means every 10ms which is a frequency that may very well be used by user code.

Some additional further reading (thanks to @marselester for linking on Discord):

> Brendan Gregg mentions the following profiling frequencies in Systems Performance book.
> 99 Hertz is used to avoid lock-step sampling that may occur at 100 Hertz, which would produce a skewed profile.
> ...
> a typical CPU profiler at Netflix collects stack traces at 49 Hertz across 32 CPUs for 30 seconds: this produces a total of 47,040 samples.

19 is both 1 less than 20, which would have been a natural choice just for lowering overhead, but it both follows the rule outlined by Brendan Gregg, and even better, it is prime.

**Comment by javierhonduco** [comment]
Implemented in the PR above by @marselester
