### ISSUE TITLE
just use gnu build id.

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca-agent#1323]
for now, we get two type of build id:
go buildid and gnu buildid.

it is not easy for package github.com/google/pprof to process it.
because this package only use gnu buildid to check if the objectfile is what we want.

**Comment by kakkoyun** [comment]
@zdyj3170101136 What would be the advantage of this?

**Comment by zdyj3170101136** [comment]
> @zdyj3170101136这样做有什么好处？

only with consistent buildid with package github.com/google/pprof.
the source code could right view.

see https://github.com/google/pprof/pull/755/files

**Comment by zdyj3170101136** [comment]
forget it.
some go file and elf file do not have gnu buildid.

so seems i should fork package github.com/google/pprof and change it's logical of get buildid.
