### ISSUE TITLE
ci: Upgrade  build pipeline to support. golang to v1.20.0

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1339]
Currently, the auto-upgrade is broken because of the failures in the pre-commit and the golangci linter stages https://github.com/parca-dev/parca-agent/pull/1289 

Somehow, embedding the eBPF object causes the problem; we need to investigate which change in the Go changelog causes this. Or is this a bug on the linters' side?

I was investigating the issue on https://github.com/parca-dev/parca-agent/pull/1293, but I still need to find the root cause.
I'm parking this for now and opening the issue to give a chance to a contributor who has more free cycles than me.

**Comment by maxbrunet** [comment]
Done in #1293
