### ISSUE TITLE
ci: Support newest version of Minikube

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1340]
The auto-upgrade is broken; apparently, some changes on Minikube causes our end-to-end tests to fail https://github.com/parca-dev/parca-agent/pull/1425

The root cause needs to be tracked down, and we should check whether we can upgrade to the most recent minikube version.

(I haven't even tested to upgrade the newest version locally).

**Comment by maxbrunet** [comment]
Submitted the fixes here: medyagh/setup-minikube#74

**Comment by maxbrunet** [comment]
One more bug before we can upgrade: medyagh/setup-minikube#110

**Comment by maxbrunet** [comment]
Worked around upstream issue for now
