### ISSUE TITLE
Don't unnecessarily strip debuginfos

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1369]
While debugging a particular situation where we pick up a debuginfo file from a debian dbgsym directory we still attempt to extract the debuginfos when they already don't contain the `.text` section, which is all we want to achieve.

We should first check whether an ELF file contains a `.text` section at all before performing the extraction.

**Comment by palash25** [comment]
hi 👋🏽  i would like to work on this

**Comment by brancz** [comment]
Go for it!
