### ISSUE TITLE
ci: Release assets does not contain version field

### ISSUE THREAD

**Issue by zdyxry** [parca-dev/parca-agent#1386]
Referring to the Parca Agent [documentation](https://www.parca.dev/docs/agent-binary) installation, I found that the v0.12.0 version of the distribution assets does not contain a version field

v0.11.1 version: `parca-agent_0.11.1_Linux_arm64.tar.gz`

v0.12.0 version: `parca-agent_Linux_arm64.tar.gz`

**Comment by kakkoyun** [comment]
We see the same behavior in the latest release https://github.com/parca-dev/parca-agent/releases/tag/v0.13.0

We should check our goreleaser configuration, probably something has been changed unintentionally, or the tool has changed its API.

**Comment by kakkoyun** [comment]
We have the same problem with Parca server so it's probably some API change in goreleaser https://github.com/parca-dev/parca/releases/tag/v0.16.0

**Comment by zdyxry** [comment]
[    GORELEASER_VERSION: v1.13.1
](https://github.com/parca-dev/parca-agent/actions/runs/3739848477/jobs/6347567982#step:9:5)

Looks like v1.13.1 is the correct version.

**Comment by kakkoyun** [comment]
> [ GORELEASER_VERSION: v1.13.1 ](https://github.com/parca-dev/parca-agent/actions/runs/3739848477/jobs/6347567982#step:9:5)
> 
> Looks like v1.13.1 is the correct version.

The version can be correct, but probably the configuration for the filenames has changed. We need to check what we miss.

I think I've messed it up in this PR https://github.com/parca-dev/parca-agent/pull/1185/files We need to add the missing version in the archive path. I'll be looking into it.

**Comment by kakkoyun** [comment]
@zdyxry Thanks a lot for reporting this. Great catch ❤️
