### ISSUE TITLE
Add Prometheus metrics on stack unwinding success/failures

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1408]
We already gather this information in BPF, but don't expose this to Prometheus yet. This is super valuable information to be able to tell how well we are doing in regards to unwinding stacks.

**Comment by javierhonduco** [comment]
https://github.com/parca-dev/parca-agent/pull/1450 fixes this (still under reivew)

**Comment by kakkoyun** [comment]
fixed by #1450
