### ISSUE TITLE
Unexpected heap spike at the start of running Parca Agent

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1436]
A Polar Signals Cloud user reported out-of-memory (OOM) killed Parca Agents with a memory limit of 500mb. Raising the memory limit to 2gb removed OOM kill and the process goes to roughly 100mb steady state which is roughly what we expect. That kind of memory spike is not acceptable though so we need to investigate.

Here is a memory profile from shortly after the process starting: https://pprof.me/a07f92d/

Comparing memory in use and bytes allocated I suspect it has something to do with discovering the compiler used to compile the binary (the binary in question is a fairly large Rust binary).

**Comment by javierhonduco** [comment]
Fixed by @brancz in https://github.com/xyproto/ainur/pull/5 + https://github.com/parca-dev/parca-agent/commit/d94d7d0b9f676bb73a4f766041a80f3d6676f847 🎉
