### ISSUE TITLE
Support multi-arch container images

### ISSUE THREAD

**Issue by lilic** [parca-dev/parca-agent#144]
Currently, the Dockerfile can only build x86_64 images, due to the following lines: 
https://github.com/parca-dev/parca-agent/blob/8338e7725d3cda39f1f5ae2c79be2d6370fd1c97/Dockerfile#L33-L40

On the latest Mac this location is actually `aarch64-linux-gnu `for example. Changing it in the Dockerfile to the correct location makes docker build correctly produce an image.

**Comment by paulfantom** [comment]
Dup of https://github.com/parca-dev/parca-agent/issues/54?

**Comment by lilic** [comment]
Technically that issue only mentions arm64, but I am fine by closing this if you don't mind changing your title maybe?

**Comment by paulfantom** [comment]
Changed.

Side note: `arm64` is the same as `aarch64` :)

**Comment by lilic** [comment]
> Side note: arm64 is the same as aarch64 :)

Yes, I meant for other arch as well, hence multi-arch.

Thanks, closing this in favour of that then!
