### ISSUE TITLE
Implement per-process Java profiler

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#1508]
Part of  #1115 
Pseudo code

```
package javaprofiler

type Profiler struct {
    // ... fields
}

func New(
    pid int,
    w profiler.ProfileWriter,
    duration time.Duration,
) *Profiler {
    // ...
}

func (p *Profiler) Run(ctx context.Context) error {
    // essentially https://github.com/async-profiler/async-profiler/blob/32601bccd9e49adda9510a2ed79d142ac6ef0ff9/profiler.sh#L364-L380
    // And then convert JFR to pprof and write via profile writer
}

func (p *Profiler) profileLoop(ctx context.Context) (*profile.Profile, error) {
  // use async profiler low-level Go package, to collect JFR profile
  // convert JFR profile to pprof and return
}
```

cc @v-thakkar

**Comment by v-thakkar** [comment]
For this, we can't use the same implementation as the current cpu profiler for other languages as we'll only be able to attach this profiler after metadata gets attached to the process and we know that it's a java process. This means that profiling will start for java processes after the first profiling round(s). So the implementation flow will look something like this:

- Find the java process and attach the metadata to it
- Start the java profiler for that process with certain parameters (required by async-profiler)
- Stop the java profiler in 2 cases: if parca-agent exits or if the process exits

Another way would be to check for each pid if it's a Java process, although this can get quite complicated and may waste some resources. So currently above solution looks best but let me know if there are some other ideas.

**Comment by javierhonduco** [comment]
Sounds reasonable! Kemal and I were thinking on adding information about the runtime using the new facilities in the Process Information work

**Comment by kakkoyun** [comment]
Deprecated.

We will use #1 to track the latest implementation.
