### ISSUE TITLE
Segmentation fault in Systemd header decoder

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1511]
Saw this stack from our production environment:

```go
github.com/parca-dev/parca-agent/pkg/discovery/systemd.(*Client).ListUnits(0xc000b08000, 0xc000a8aba0?, 0xc000191a00?)
	github.com/parca-dev/parca-agent/pkg/discovery/systemd/message.go:159 +0x99
github.com/parca-dev/parca-agent/pkg/discovery/systemd.(*messageDecoder).DecodeListUnits(0xc00074c4b0, {0x231d880?, 0xc000b08060}, 0x33bea80?, 0xc001361a48)
	github.com/parca-dev/parca-agent/pkg/discovery/systemd/header.go:126 +0x149
github.com/parca-dev/parca-agent/pkg/discovery/systemd.decodeHeader(0xc000b06030, 0x206bad6?, 0xc00074c578, 0x1)
goroutine 88 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x19eb869]
panic: runtime error: invalid memory address or nil pointer dereference
level=warn name=parca-agent ts=2023-03-30T08:29:50.691486947Z caller=systemd.go:65 discovery=systemd msg="failed to get units from systemd D-Bus API" err="decode ListUnits: message body: read unix @->/run/dbus/system_bus_socket: i/o timeout"
```

It happens relatively frequently:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/959128/228834605-acf173a5-9775-4202-861d-fda531b1a807.png">

cc @marselester @kakkoyun

**Comment by javierhonduco** [comment]
Seems like we got a buffer that's not big enough

https://github.com/parca-dev/parca-agent/blob/42e40d368eff762d41e1619c523e9f611eccbaa3/pkg/discovery/systemd/header.go#LL126

**Comment by marselester** [comment]
> decode ListUnits: message body: read unix @->/run/dbus/system_bus_socket: i/o timeout

It looks like systemd package returned `i/o timeout` because it couldn't decode a message header in time (`read` syscall blocked for > 1s) and then next call to fetch units caused the panic https://github.com/parca-dev/parca-agent/blob/main/pkg/discovery/systemd.go#L63-L67:

```go
update, err := d.unitsUpdate(c)
if err != nil {
	level.Warn(d.logger).Log("msg", "failed to get units from systemd D-Bus API", "err", err)
	continue
}
```

Are there more logs around `panic`?

**Comment by marselester** [comment]
Found a culprit https://github.com/parca-dev/parca-agent/pull/1513, but I haven't figured yet why/how exactly the message header gets corrupted.

**Comment by javierhonduco** [comment]
We haven't gotten any panics for the past 12h!

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/959128/229826073-f638e98e-d34f-446f-a166-cd83871184cb.png">


Let's keep this issue open for a couple more days, though

**Comment by marselester** [comment]
That's great!

**Comment by brancz** [comment]
I think we can close this, we've been running it for several days now and there are zero occurrences where previously we had ~150 per day per container.
