### ISSUE TITLE
Add a test for vdso package

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca-agent#1559]
While looking at the vdso bug found earlier this week, I realized that we don't have a test for `resolve` function. I think it'll be nice to have it to make sure that it doesn't resolve invalid VDSO addresses.

JFYI, I already have a half-written test from Wed. Will need to spend ~1 hour sometime next week to finish it. So just opening this for visibility.

**Comment by kakkoyun** [comment]
> can I take this up? @javierhonduco @kakkoyun

Please, by all means, go ahead. We would love to accept community contributions :)
