### ISSUE TITLE
Reduce kernel symbolizer memory usage

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1585]

**Comment by kakkoyun** [comment]
@javierhonduco, this is fixed by https://github.com/parca-dev/parca-agent/pull/1587, no?

**Comment by javierhonduco** [comment]
Will close once we bake this in Demo/Prod for a bit longer and our customers confirm this is resolved for them

**Comment by javierhonduco** [comment]
The memory reduction and OOMs dropping to zero were confirmed by our metrics and our customers'
