### ISSUE TITLE
Sign releases with sigstore

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#16]
Since users need to run parca agent as root or with `CAP_SYS_ADMIN`, we want to do our utmost best to secure the supply chain of parca agent. An additional thing to the things that we are already doing today, would be to sign our artifacts. A popular and well maintained solution is https://www.sigstore.dev/

**Comment by brancz** [comment]
Another related post: https://shibumi.dev/posts/keyless-signatures-with-github-actions/

**Comment by kakkoyun** [comment]
Closed by #402
