### ISSUE TITLE
Normalization issues

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1613]
i.e. while running `kubectl run -n parca debug --image=python:latest -it`

aka "the cockroachdb bug" (still present in `main`)

**Comment by kakkoyun** [comment]
@javierhonduco What's the expected output here? It's a bit vague, and it's been awhile.

**Comment by kakkoyun** [comment]
Currently this is how it looks like with Parca server as backend:
![CleanShot 2023-06-16 at 12 50 52](https://github.com/parca-dev/parca-agent/assets/536449/0a8db076-2912-4a3e-a0e6-7265f3d83988)

**Comment by javierhonduco** [comment]
The profile looks correct! 

We need to look for normalization errors in the logs to ensure this issue doesn't happen again. They tend to happen more in demo/production for some reason, and they don't show up consistently, so I think we should restart the Agent several times (perhaps 20 times or so) with a mix of Python processes already running / starting after the agent

**Comment by kakkoyun** [comment]
I'll also test it against the cloud/demo.

**Comment by kakkoyun** [comment]
Everything looks fine now

Parca Agent:

![CleanShot 2023-06-16 at 13 37 22](https://github.com/parca-dev/parca-agent/assets/536449/35cb6d8a-eaf5-437b-9714-f3d2c5310c68)

https://pprof.me/4fafe77

Python containers:

![CleanShot 2023-06-16 at 13 38 11](https://github.com/parca-dev/parca-agent/assets/536449/bc85e7b2-1ef2-489f-9440-34d9072438f1)

https://pprof.me/e68799e
