### ISSUE TITLE
Resource usage of rework process info

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#1616]
[metrics link](https://demo.pyrra.dev/prometheus/graph?g0.expr=process_resident_memory_bytes%7Bcontainer%3D%22parca-agent%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2d&g1.expr=process_open_fds%7Bcontainer%3D%22parca-agent%22%7D&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=2d&g2.expr=rate(process_cpu_seconds_total%7Bcontainer%3D%22parca-agent%22%7D%5B5m%5D)&g2.tab=0&g2.stacked=0&g2.show_exemplars=0&g2.range_input=12h)

**one pod uses significantly more CPU**
<img width="1217" alt="image" src="https://github.com/parca-dev/parca-agent/assets/959128/f1f9480d-0419-4171-97e4-b42be05297c2">

**one pod used 3x as much mem**

<img width="607" alt="image" src="https://github.com/parca-dev/parca-agent/assets/959128/215e17ed-7a6a-41d0-a74c-09e0ba6bfebf">

**FD don't seem to be closed quickly after processing the debug infos**

<img width="1239" alt="image" src="https://github.com/parca-dev/parca-agent/assets/959128/2574db3a-f484-475b-b95a-cbb9976d2e01">

**Comment by kakkoyun** [comment]
The latest status after several improvements: (namespace="parca-devel" the latest main and namespace="parca" the latest stable release)

https://demo.pyrra.dev/prometheus/graph?g0.expr=avg%20by%20(namespace)%20(process_resident_memory_bytes%7Bcontainer%3D%22parca-agent%22%7D)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2d&g1.expr=avg%20by%20(namespace)%20(process_open_fds%7Bcontainer%3D%22parca-agent%22%7D)&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=2d&g2.expr=avg%20by%20(namespace)%20(rate(process_cpu_seconds_total%7Bcontainer%3D%22parca-agent%22%7D%5B5m%5D))&g2.tab=0&g2.stacked=0&g2.show_exemplars=0&g2.range_input=2d

<img width="1800" alt="CleanShot 2023-06-18 at 09 50 17@2x" src="https://github.com/parca-dev/parca-agent/assets/536449/f01b42fd-bb20-49b6-b833-9cf1c47d8293">

<img width="1798" alt="CleanShot 2023-06-18 at 09 49 59@2x" src="https://github.com/parca-dev/parca-agent/assets/536449/7f807e06-934a-461b-9f33-a4fea526db96">

<img width="1796" alt="CleanShot 2023-06-18 at 09 49 45@2x" src="https://github.com/parca-dev/parca-agent/assets/536449/624841f0-1397-4c2b-9088-635eeb84d2c4">

The number of open FDs is higher but matched to the capacity of the object pool. It can be reduced. I'll introduce a flag tomorrow.
