### ISSUE TITLE
Panic during runtime

### ISSUE THREAD

**Issue by thorfour** [parca-dev/parca-agent#1635]
**Describe the bug**

![](https://media.giphy.com/media/1EghTrigJJhq8/giphy.gif)

```
panic: runtime error: index out of range [0] with length 0

goroutine 131 [running]:
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*bpfMaps).setUnwindTableForMapping(0xc0007da120, 0xfe?, 0xc0025d8848?, 0xc000ef6d20)
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/maps.go:1131 +0x1dc5
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*bpfMaps).addUnwindTableForProcess(0xc0007da120, 0x2b1, {0x0, 0x0, 0x0}, 0x1)
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/maps.go:623 +0x625
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).addUnwindTableForProcess(0xc00028a840, 0xc000592f32?)
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:305 +0x208
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run.func2.1({0xc0004cfe30, 0x1, 0x0?})
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:532 +0x54
github.com/parca-dev/parca-agent/pkg/profiler/cpu.onDemandUnwindInfoBatcher({0x239f8f8, 0xc0006ec180}, 0xc0005fcde0, 0x0?, 0xc000f37fc0)
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:347 +0x20f
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run.func2()
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:530 +0x4a
created by github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run
	github.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:529 +0x1253
```

**To Reproduce**
I was running on Kernel 5.10.0-21-cloud-amd64 from Google Cloud with the `--debuginfo-strip` flag set. 

**Expected behavior**
To not panic

**Screenshots** or **Profiles** (using https://pprof.me)
N/A

**Logs**
See panic above

**Software (please complete the following information):**
 - Parca Agent Version: parca-agent, version 0.19.0 (commit: 4094583a4567e3061e0ab357f17e3109b0514e2c, date: 2023-04-26T14:19:53Z), arch: amd64
 - Parca Server Version (if applicable): N/A

**Workload (please complete the following information):**
- Runtime (if applicable):
- Compiler (if applicable):

**Environment (please complete the following information):**
- Linux Distribution: 
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Linux Version: `5.10.0-21-cloud-amd64`
- Arch: [`x86_64`]
- Kubernetes Version (if applicable): N/A
- Container Runtime (if applicable): N/A

**Additional context**

**Comment by javierhonduco** [comment]
Taking a look, thanks for reporting!

**Comment by javierhonduco** [comment]
Right off the bat, I am not sure how this can be happening. Will continue thinking about this. 

Meanwhile, if this is easy for you to reproduce, could you set the debug logs to `debug` and grab a bunch of lines before the panic? I am particularly interested in anything matching `chunk size` but having the general context would be ace!

**Comment by javierhonduco** [comment]
Other info that Thor told me about:
- This was in a VM with 1 GB;
- It's easily reproducible, but fails after some amount of time running;
- It's not a blocker for him atm;

**Comment by javierhonduco** [comment]
@thorfour do you mind trying again with the latest release and checking if this reproduces? Thanks! If the kernel version or anything else changes too, can you share the new versions? No rush btw

**Comment by thorfour** [comment]
> @thorfour do you mind trying again with the latest release and checking if this reproduces? Thanks! If the kernel version or anything else changes too, can you share the new versions? No rush btw

Will try and repro this week

**Comment by thorfour** [comment]
@javierhonduco after 3h of running the agent no longer panics on the same setup as I had before. Going to close this issue as resolved. Thanks!
