### ISSUE TITLE
[bpf profile_cpu] "has_unwind_information" works rather than "has_fp"  even though a porgrame(C) compiled with frame pointers

### ISSUE THREAD

**Issue by t00350320** [parca-dev/parca-agent#1657]
**Describe the bug**

c code compiled with frame pointers("-fno-omit-frame-pointer"), but has_unwind_information works rather than profile_cpu.has_fp
**To Reproduce**

gcc -fno-omit-frame-pointer -o hello_no hello.c

start parca-agent with "
```
./parca-agent --log-level=debug --node=binary-test --remote-store-address=localhost:7070 --remote-store-insecure --verbose-bpf-logging   >"agent.log" 2>&1&
```
**Expected behavior**
has_fp works, and has_unwind_information no need work

**Screenshots** or **Profiles** (using https://pprof.me)
```
cat /sys/kernel/debug/tracing/trace_pipe
        hello_no-10741   [000] d.h3.  3772.676956: bpf_trace_printk: ~about to check shards found=1
        hello_no-10741   [000] d.h3.  3772.676960: bpf_trace_printk: ~checking shards now
        hello_no-10741   [000] d.h3.  3772.676961: bpf_trace_printk: [info] found chunk
        hello_no-10741   [000] d.h3.  3772.676963: bpf_trace_printk: pid 10741 tgid 10741
        hello_no-10741   [000] d.h3.  3772.676964: bpf_trace_printk: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        hello_no-10741   [000] d.h3.  3772.676964: bpf_trace_printk: traversing stack using .eh_frame information!!
        hello_no-10741   [000] d.h3.  3772.676965: bpf_trace_printk: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        hello_no-10741   [000] d.h3.  3772.676965: bpf_trace_printk: ## frame: 0
        hello_no-10741   [000] d.h3.  3772.676966: bpf_trace_printk: 	current pc: 7f36d2ce57fa
        hello_no-10741   [000] d.h3.  3772.676967: bpf_trace_printk: 	current sp: 7ffe60178cb0
        hello_no-10741   [000] d.h3.  3772.676967: bpf_trace_printk: 	current bp: 7ffe60178d80
        hello_no-10741   [000] d.h3.  3772.676968: bpf_trace_printk: ~about to check shards found=1
        hello_no-10741   [000] d.h3.  3772.676968: bpf_trace_printk: ~checking shards now
        hello_no-10741   [000] d.h3.  3772.676969: bpf_trace_printk: [info] found chunk
        hello_no-10741   [000] d.h3.  3772.676970: bpf_trace_printk: le offset: 7f36d2c00000
        hello_no-10741   [000] d.h3.  3772.676971: bpf_trace_printk: ========== left 100986 right 130032
```

**Logs**
```
root       10741   10557  3 03:27 pts/1    00:00:02 ./hello_no
level=debug name=parca-agent ts=2023-05-17T02:27:22.112983904Z caller=cpu.go:303 msg="adding unwind tables" pid=10741
level=debug name=parca-agent ts=2023-05-17T02:27:22.113716415Z caller=maps.go:933 component=maps msg="special section" pid=10741
level=debug name=parca-agent ts=2023-05-17T02:27:22.113736372Z caller=maps.go:933 component=maps msg="special section" pid=10741
level=debug name=parca-agent ts=2023-05-17T02:27:39.862153072Z caller=manager.go:194 msg="label cache miss" provider=parca_agent_cpu pid=10741
```

**Software (please complete the following information):**
 - Parca Agent Version: 0.19.0   
 - parca, version 0.17.0 (commit: fa84a70c7f6bca195a64242384c69c3d93a377a5)

**Environment (please complete the following information):**
- Linux Distribution: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
- Linux Version: [5.19.0-41-generic`]
- Arch: [`x86_64`]

**Comment by javierhonduco** [comment]
If you would like to avoid kicking in the DWARF unwinder you could patch the Agent locally to detect `$rbp == 0 | $rbp == 1`as a stop condition, but we are unlikely to accept this change in the project at this time

**Comment by t00350320** [comment]
yep,thanks a lot.just thought about it that way.
 i think fp simplify the ebpf logic while unwind table may cost much memory and walk time in our large-scale program（Please correct any inaccuracies ）.
i will try to test the cpu/mem loss through different methods （fp and unwind method ）.
anyway，you may close this issue ^_^

**Comment by javierhonduco** [comment]
Definitely! DWARF will always use significantly more memory, as the unwind info has to be stored in BPF maps. In terms of CPU the overhead is definitely higher than FP-unwinding too, but shouldn't be prohibitive for most workloads -- right now we run the BPF program 19 times a second, but this can be customized.

Let me know if you find the overhead to be too high for you or any other feedback you might have! Cheers! :)
