### ISSUE TITLE
metadata: Increase the cache time to live when providers are stabilize

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1665]
> Random thought: the cache expiry seems fairly short, if we end up seeing a lot of CPU time spent in re-retrieving metadata, I would suggest we perform some sort of heuristic to determine whether labelsets have stabilized. Eg. label-sets haven't changed in 3 cycles, so cache them very aggressively for longer periods (3 cycles is just a random heuristic, it could also increase exponentially). 
by @brancz 

👍 Good idea. This could work out easily by adding a `last updated at` to the providers and an additional long-term cache to the label manager. (Unfortunately, our current caching library doesn't allow setting expiration per item. It's just an implementation we can achieve it by using rissetto etc).

_Originally posted by @kakkoyun in https://github.com/parca-dev/parca-agent/issues/1653#issuecomment-1551353917_

**Comment by brancz** [comment]
Judging by latest profiling data I no longer think this is necessary
