### ISSUE TITLE
ci: Run `vmtests` before `go-build` tests

### ISSUE THREAD

**Issue by Sylfrena** [parca-dev/parca-agent#1707]
PR #1670 initially [failed](https://github.com/parca-dev/parca-agent/actions/runs/5077018361/jobs/9119798755?pr=1670#step:16:659) the Go build step because of failing tests in the `profiler` pkg. However, this was not reproducible locally which made it difficult to narrow down the bug.

It ultimately turned out to be an [unsupported bpf helper](https://github.com/libbpf/libbpf/blob/f7eb43b90f4c8882edf6354f8585094f8f3aade0/src/bpf_helpers.h#L287-L289) in older kernels(5.xx) which should have been caught by the `vmtests` but we never made it to the [`vmtests`](https://github.com/parca-dev/parca-agent/blob/3b6b895963cb895efa77511f131133212b0e45fb/.github/workflows/build.yml#L140) as they are scheduled after the [Go build tests](https://github.com/parca-dev/parca-agent/blob/3b6b895963cb895efa77511f131133212b0e45fb/.github/workflows/build.yml#L50).

**Comment by javierhonduco** [comment]
Just for future folks reading this, the profiler tests failed because we run the profiler tests in the GitHub Actions machine which happens to run an older kernel. I do agree that perhaps running kernel tests first might be a good idea, but either way, it's always good to run them locally with `make vmtest` to see if there are any incompatibilities in the kernels we aim to support!

**Comment by Namanl2001** [comment]
I [tried](https://github.com/Namanl2001/parca-agent/pull/2/files) running `vmtests` before go-build tests but the job [failed](https://github.com/Namanl2001/parca-agent/actions/runs/5411086338/jobs/9833401144#step:4:11), the reason being `vmtests` [requires](https://github.com/Namanl2001/parca-agent/pull/2/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R64-R68) `initramfs` which is build and uploaded by the `go-build-test`.

will it be a good idea to shift the `initramfs` related tasks to the `vmtests` job?

**Comment by javierhonduco** [comment]
It can definitely be moved there! We would have to also build the test in `vmtest`, but I don't think it should be too much of an issue. Thanks for working on this!

**Comment by Namanl2001** [comment]
this issue can be closed now in favor of #1814
