### ISSUE TITLE
metadata/discovery: Support hybrid cgroup v1/v2

### ISSUE THREAD

**Issue by derekparker** [parca-dev/parca-agent#180]
Currently parca-agent can support cgroup v1 and v2, however we don't have a great story around what happens in hybrid mode when both are mounted.

From our perspective we care mostly about the perf_events controller. In cgroup v2 this is always implicitly enabled, so we don't have to do anything special within the agent. With cgroup v1 we have to enable the controller manually in some instances and then add processes to it.

In hybrid mode we are going to want to stick with either v1 or v2 and not mix and match them. This may involve inspecting the cgroup fs and making a determination per systemd unit / pod / etc... what version is being used and stick with that going forward for that specific service.

**Comment by kakkoyun** [comment]
cc @javierhonduco

**Comment by kakkoyun** [comment]
deprecated after #627
