### ISSUE TITLE
https://demo.parca.dev/ seems to be down

### ISSUE THREAD

**Issue by fzyzcjy** [parca-dev/parca-agent#1842]
At least I cannot open https://demo.parca.dev/ here. It says `ERR_CONNECTION_CLOSED`.

**Comment by brancz** [comment]
Apologies, we’re migrating providers and are having some trouble.

**Comment by fzyzcjy** [comment]
No worries, take your time!

**Comment by metalmatze** [comment]
Should be back up again.
