### ISSUE TITLE
parca-debug-info doesn't work with Rust binaries

### ISSUE THREAD

**Issue by ordian** [parca-dev/parca-agent#185]
Steps to reproduce:
```
$ cargo new --bin parca-test
$ cd parca-test
$ cargo build --quiet
$ parca-debug-info extract --log-level="debug" ./target/debug/parca-test
level=debug ts=2022-01-04T15:50:08.435179792Z caller=debuginfo.go:278 msg="using eu-strip" file=./target/debug/parca-test
level=error ts=2022-01-04T15:50:08.441557328Z caller=debuginfo.go:259 msg="external binutils command call failed" output="eu-strip: Cannot remove allocated section '.debug_gdb_scripts'" file=./target/debug/parca-test
level=error ts=2022-01-04T15:50:08.441599333Z caller=debuginfo.go:130 msg="failed to extract debug information" buildid=f17a111406287bd2e6a658a8ac539e3b6bfa35ac file=./target/debug/parca-test err="failed to extract debug information from binary: exit status 1"
level=info ts=2022-01-04T15:50:08.441618562Z caller=main.go:170 msg=done!
```

**Comment by kakkoyun** [comment]
Thanks for the report. I'll look into it. It should be a small fix.

**Comment by kakkoyun** [comment]
`rustc` sets flags (e.g SHF_ALLOC) for `.debug_gdb_scripts` section. Which causes eu-strip/objcopy to refuse to remove that certain section.

`Name: .debug_gdb_scripts Size: 34 B Type: SHT_PROGBITS Flags: SHF_ALLOC+SHF_MERGE+SHF_STRINGS`

In #189 we check all the debug sections and only remove them if they do not have any bits. This clean up was introduced in https://github.com/parca-dev/parca-agent/pull/102 for another special case for Go binaries where we had  `.debug_gdb_scripts` section without any bits.

I hope the PR will be a solution for both.
