### ISSUE TITLE
BPF program fails to load with `BPF program is too large` in Linux 6.4

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#1880]
**Describe the bug**

BPF program started to fail to load.

**Logs**
```
...
BPF program is too large. Processed 1000001 insn\nprocessed 1000001 insns (limit 1000000) max_states_per_insn 29 total_states 26022 peak_states 2104 mark_read 77\n-- END PROG LOAD LOG --\n"
level=debug name=parca-agent ts=2023-07-24T15:11:21.226491498Z caller=cpu.go:207 component=cpu_profiler msg="libbpf: prog 'walk_user_stacktrace_impl': failed to load: -7\n"
level=debug name=parca-agent ts=2023-07-24T15:11:21.226560538Z caller=cpu.go:207 component=cpu_profiler msg="libbpf: failed to load object 'parca'\n"
level=error name=parca-agent ts=2023-07-24T15:11:21.226587168Z caller=cpu.go:277 component=cpu_profiler msg="Could not create unwind info shards" lastError="failed to load BPF object: argument list too long"
```

**Software (please complete the following information):**
 - Parca Agent Version: [`parca-agent --version`] v0.23.2 and main

**Environment (please complete the following information):**
- Linux Distribution: [`cat /etc/*-release`] `Arch Linux`
- Linux Version: [`uname -r`] `Linux hertzner-devbox-archlinux 6.4.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 19:19:38 +0000 x86_64 GNU/Linux`

**Comment by kakkoyun** [comment]
Downgrading to `Linux hertzner-devbox-archlinux 6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux`

**Comment by luisgerhorst** [comment]
Ack, same with the latest kernel (6.5.0-rc2) on Debian.

**Comment by javierhonduco** [comment]
I'm running `Linux fedora 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64 GNU/Linux` without any issues.

**Comment by javierhonduco** [comment]
Narrowed it down between these two stable (https://github.com/gregkh/linux) revisions. Will bisect them in the next couple of days.

## Bad 🔴 

```
6.4.7
8c3800660977da085a7d55c3f6213dffb8c89692        refs/tags/v6.4.7
```

## Good 🟢 

```
6.3.13
1788df9af3e8cc33c8d58c9947aa3bac26cd9538        refs/tags/v6.3.13
```

**Comment by javierhonduco** [comment]
Bisecting between `v6.4.3` and `v6.4.5` points at:

```
ae3c237881581e74dd911eb919771ee9c419fc5f bpf: Verify scalar ids mapping in regsafe() using check_ids()
```

I'm going to double-check tomorrow that the bisect is correct and will report the bug

**Comment by javierhonduco** [comment]
Just to be sure, I've just tried with the 5 commits before `ae3c237881581e74dd911eb919771ee9c419fc5f`, the first commit that shows the issue, in stable and they all pass. While I am not sure I understand the verifier change and how that can map to more code paths being explored, I think that's the bad commit.

Tried also on Linus' tree with the same outcome. Adding the revisions in his tree for completeness.

```
commit 1ffc85d9298e0ca0137ba65c93a786143fe167b8
Author: Eduard Zingerman <eddyz87@gmail.com>
Date:   Tue Jun 13 18:38:23 2023 +0300

bpf: Verify scalar ids mapping in regsafe() using check_ids()
````

Fails while the previous commit doesn't exhibit this issue (`dec020280373c60d6df48d1954e72dd6c5640282`).

**Comment by javierhonduco** [comment]
On the bad kernel revision, this patch passes the verifier, so this could be a good remediation in the meantime. The extra tail calls will incur some overhead for big stacks that would be good to measure but at least it would unblock the newest kernels. I still think we should report it as a potential regression and see what the BPF devs say.

(Note, reducing the program's size in other ways works as well, e.g.`MAX_BINARY_SEARCH_DEPTH` from 19 to 16, but this will force us to decrease the size of the unwind shards)

```patch
[javierhonduco@fedora parca-agent]$ git diff
diff --git a/bpf/cpu/cpu.bpf.c b/bpf/cpu/cpu.bpf.c
index 1f942f4e..def2c15e 100644
--- a/bpf/cpu/cpu.bpf.c
+++ b/bpf/cpu/cpu.bpf.c
@@ -17,9 +17,9 @@
 /*================================ CONSTANTS =================================*/
 
 // Number of frames to walk per tail call iteration.
-#define MAX_STACK_DEPTH_PER_PROGRAM 15
+#define MAX_STACK_DEPTH_PER_PROGRAM 11
 // Number of BPF tail calls that will be attempted.
-#define MAX_TAIL_CALLS 10
+#define MAX_TAIL_CALLS 12
 // Maximum number of frames.
 #define MAX_STACK_DEPTH 127
 _Static_assert(MAX_TAIL_CALLS *MAX_STACK_DEPTH_PER_PROGRAM >= MAX_STACK_DEPTH, "enough iterations to traverse the whole stack");
```

@kakkoyun @luisgerhorst could you confirm if this patch fixes the problem for you in your distros running 6.4+?
