### ISSUE TITLE
how to build agent on centos 8.5

### ISSUE THREAD

**Issue by NameHaibinZhang** [parca-dev/parca-agent#1906]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NameHaibinZhang** [comment]
# github.com/parca-dev/parca-agent/cmd/parca-agent
/root/.gvm/gos/go1.20/pkg/tool/linux_amd64/link: running clang failed: exit status 1
/usr/bin/ld: 找不到 -lzstd
/usr/bin/ld: 找不到 -lzstd
/usr/bin/ld: 找不到 -lzstd
/usr/bin/ld: 找不到 -lelf
/usr/bin/ld: 找不到 -lz
/usr/bin/ld: 找不到 -lzstd
/usr/bin/ld: 找不到 -lpthread
/usr/bin/ld: 找不到 -lc
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by javierhonduco** [comment]
Hi, 

The linker is failing as it can't find some native dependencies that Parca Agent requires. You might want to install them (`libzstd-devel`, `elfutils-libelf-devel`, `zlib-devel`, etc).

If you want to do a static build, you might need alternative packages.

Another way is to use our [container build setup via Make](https://github.com/parca-dev/parca-agent/blob/6ae314e02e490fa14cf119da50ba2c599e27fcd7/Makefile#L285-L297). I have not used it much, but @kakkoyun is the expert here so he might be able to help you out if you want to go down this route!

**Comment by javierhonduco** [comment]
Closing the issue, but let us know if installing the dependencies / using the docker build method doesn't work for you
