### ISSUE TITLE
Quick start failed with ebpf check

### ISSUE THREAD

**Issue by joeyleeeeeee97** [parca-dev/parca-agent#1979]
**Describe the bug**
$ ./parca-agent --node=test --remote-store-address=localhost:7070 --remote-store-insecure
ooooooooo.                                                  .o.                                            .
`888   `Y88.                                               .888.                                         .o8
 888   .d88'  .oooo.   oooo d8b  .ooooo.   .oooo.         .8"888.      .oooooooo  .ooooo.  ooo. .oo.   .o888oo
 888ooo88P'  `P  )88b  `888""8P d88' `"Y8 `P  )88b       .8' `888.    888' `88b  d88' `88b `888P"Y88b    888
 888          .oP"888   888     888        .oP"888      .88ooo8888.   888   888  888ooo888  888   888    888
 888         d8(  888   888     888   .o8 d8(  888     .8'     `888.  `88bod8P'  888    .o  888   888    888 .
o888o        `Y888""8o d888b    `Y8bod8P' `Y888""8o   o88o     o8888o `8oooooo.  `Y8bod8P' o888o o888o   "888"
                                                                      d"     YD
                                                                      "Y88888P'

level=info name=parca-agent ts=2023-09-05T09:13:55.974204229Z caller=main.go:330 msg="maxprocs: Leaving GOMAXPROCS=40: CPU quota undefined"
level=info name=parca-agent ts=2023-09-05T09:13:55.989982917Z caller=main.go:397 msg="eBPF is supported and enabled by the host kernel"
name=parca-agent ts=2023-09-05T09:13:56.011151701Z caller=main.go:551 msg=starting... node=test store=localhost:7070
level=warn name=parca-agent ts=2023-09-05T09:13:56.013255359Z caller=discovery_manager.go:196 msg="unable to start provider" provider=systemd/0 error="context canceled"
level=error name=parca-agent ts=2023-09-05T09:13:56.013784532Z caller=main.go:340 err="bpf check: perf event program type not supported: errno 0\nstack trace map type not supported: errno 0\nhash map type not supported: errno 0"

**To Reproduce**

**Expected behavior**

**Screenshots** or **Profiles** (using https://pprof.me)

**Logs**

**Software (please complete the following information):**
 - Parca Agent Version: [`parca-agent --version`]
 - Parca Server Version (if applicable): [`parca --version`]

**Workload (please complete the following information):**
- Runtime (if applicable):
- Compiler (if applicable):

**Environment (please complete the following information):**
- Linux Distribution: [`cat /etc/*-release`]
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Linux Version: [`uname -r`]
5.15.0-78-generic
- Arch: [`uname -m`] x86_64
- Kubernetes Version (if applicable): [`kubectl --version`] no
- Container Runtime (if applicable):no

**Additional context**

**Comment by javierhonduco** [comment]
`root` is required (in reality some other fine-grained capabilities might be enough, but not sure which ones exactly right now). Which user are you running the Agent under?

**Comment by joeyleeeeeee97** [comment]
@javierhonduco  Thank you. Under root this is fixed.
maybe we could add some tip in error message or quick start  guide.

**Comment by javierhonduco** [comment]
Added a check in the code, let us know if this doesn't work as intended!
