### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#2]
Prior art: https://github.com/benfred/py-spy#how-does-py-spy-work
Notes on native stacks (this would also be how we could add kernel space stacks): https://www.benfrederickson.com/profiling-native-python-extensions-with-py-spy/

To generate C bindings: https://github.com/xlab/c-for-go

**Comment by guettli** [comment]
Maybe this will helps you to implement profiling for Python: https://github.com/bloomberg/memray

**Comment by maxbrunet** [comment]
CPython 3.12 will add support perf maps, which will allow to profile Python like NodeJS/Java

https://docs.python.org/3.12/howto/perf_profiling.html#perf-profiling

Shared on Discord: https://discord.com/channels/877547706334199818/877547706334199821/1036782373121032204

**Comment by javierhonduco** [comment]
Implemented by the one and only, @kakkoyun!
