### ISSUE TITLE
Parca continous exporting profiles even when relabel config explicitly disallows it

### ISSUE THREAD

**Issue by isidentical** [parca-dev/parca-agent#2202]
**Describe the bug**
When parca-agent is configured to only keep profiles with a certain label, it still doesn't prevent ingesting mismatched profiles that lack that label. In our case we have a kubernetes cluster where parca-agent is deployed, and the agent is configured to only keep `app=$X` through a  `relabel_configs` entry. But I can still see profiling traces this being ingested in PolarSignals UI when I query `app!=$X`.

**To Reproduce**
This is our ConfigMap:
```
Name:         parca-config

Data
====
parca-agent.yaml:
----
relabel_configs:
- source_labels: [app]
  regex: fal-isolate-controller
  action: keep
```

And this is the Pod information:
```
[...]
    Mounts:
      /config from config (ro)
[...]
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      parca-config
    Optional:  false
```

**Expected behavior**
Not seeing any `app!=$X` on the UI.

**Screenshots** or **Profiles** (using https://pprof.me)
![image](https://github.com/parca-dev/parca-agent/assets/47358913/7afc0fea-a2a1-4a13-ade5-7bf77afa076c)

**Logs**

Don't see any errors/unusual warnings in the logs.

**Software (please complete the following information):**
 - Parca Agent Version: `ghcr.io/parca-dev/parca-agent:v0.26.0`
 - Parca Server Version (if applicable): PolarSignals

**Workload (please complete the following information):**
- Runtime (if applicable): Python
- Compiler (if applicable): -

**Environment (please complete the following information):**
- Linux Distribution: Same as the `parca-agent` docker image
- Linux Version: 5.15.107+
- Arch: x86_64
- Kubernetes Version (if applicable): v1.25.10-gke.2700
- Container Runtime (if applicable): COS

**Additional context**
Context from discord: https://discord.com/channels/813669360513056790/913454681878048868/1170356803712843946

**Comment by kakkoyun** [comment]
@isidentical Could you please share the label set on your target workload? 

Hovering over a sample should do the trick. e.g.

![CleanShot 2023-11-09 at 18 20 55](https://github.com/parca-dev/parca-agent/assets/536449/6ba80ffc-a281-4cb7-b839-0c2b119f9b18)

**Comment by isidentical** [comment]
This is a positive match (app="fal-isolate-controller")
![image](https://github.com/parca-dev/parca-agent/assets/47358913/83d14539-0cfa-43cb-b1c0-dbcbcc325b17)

And this is a negative one (app!="fal-isolate-controller") that shouldn't have been ingested (?)
![image](https://github.com/parca-dev/parca-agent/assets/47358913/1e6d370d-e390-4355-9a5b-55287de7cb76)

**Comment by isidentical** [comment]
With the suggestion of @kakkoyun, we noticed `--config-path` was missing from the set of arguments which means anything that I put was ignored 🤦🏻 There is no real issue with parca on that front, it was entirely on my side.
