### ISSUE TITLE
Make `tickerDuration` configurable 

### ISSUE THREAD

**Issue by Sylfrena** [parca-dev/parca-agent#235]
Currently, the batcher write client lacks support for a user-configurable [ticker duration](https://github.com/parca-dev/parca-agent/blob/a9cc56cf0a58d846e7d2da717a0a1948c2cbf9a3/cmd/parca-agent/main.go#L138). Add a flag to enable users to set the duration as per their requirements.

**Comment by me-diru** [comment]
hey, this looks like a good task to get started on parca-agent, may I work on this? thank you!

**Comment by kakkoyun** [comment]
@me-diru, Please go ahead :) and reach us on Discord if you have any questions.
