### ISSUE TITLE
python: Agent crash after running for a while

### ISSUE THREAD

**Issue by Ha-Dj** [parca-dev/parca-agent#2458]
This is the log output :

```
last stderr" last_stderr="ug name=parca-agent ts=2024-01-29T10:04:12.107325348Z caller=maps.go:1483 component=cpu_profiler component=bpf_maps msg=\"setUnwindTable called\" shards=4 maxshards=30 sumofunwindrows=1012827
level=debug name=parca-agent ts=2024-01-29T10:04:12.107333593Z caller=maps.go:1494 component=cpu_profiler component=bpf_maps msg=\"special section\" pid=1588
level=debug name=parca-agent ts=2024-01-29T10:04:12.107376193Z caller=maps.go:1353 component=cpu_profiler component=bpf_maps msg=\"PersistUnwindTable called\" liveunwindrows=12884
level=debug name=parca-agent ts=2024-01-29T10:04:12.869068438Z caller=cpu.go:567 component=cpu_profiler msg=\"prefetching process info\" pid=3550
level=debug name=parca-agent ts=2024-01-29T10:04:12.869163967Z caller=cpu.go:500 component=cpu_profiler msg=\"failed to call AddInterpreter\" pid=3550 err=\"index for interpreter version: unknown version 2.6.0\"
level=debug name=parca-agent ts=2024-01-29T10:04:12.869191129Z caller=cpu.go:567 component=cpu_profiler msg=\"prefetching process info\" pid=3549
level=debug name=parca-agent ts=2024-01-29T10:04:12.869650069Z caller=pool.go:175 msg=\"evicting object file\" key=\"{path:/usr/local/qcloud/monitor/python26/lib/python2.6/lib-dynload/_ctypes.so mountNamespaceID:mnt:[4026531840] modtime:{wall:123462455 ext:63840484317 loc:0x3e2f420}}\"
level=debug name=parca-agent ts=2024-01-29T10:04:12.869871334Z caller=pool.go:175 msg=\"evicting object file\" key=\"{path:/usr/local/qcloud/monitor/barad/lib/psutil/_psutil_posix.so mountNamespaceID:mnt:[4026531840] modtime:{wall:37270851 ext:63841859285 loc:0x3e2f420}}\"
level=debug name=parca-agent ts=2024-01-29T10:04:12.870009543Z caller=pool.go:175 msg=\"evicting object file\" key=\"{path:/usr/local/qcloud/monitor/barad/lib/psutil/_psutil_linux.so mountNamespaceID:mnt:[4026531840] modtime:{wall:35270851 ext:63841859285 loc:0x3e2f420}}\"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdd378c]

goroutine 291 [running]:
github.com/parca-dev/parca-agent/pkg/runtime/python.newInterpreter({0x7?, {{0x24e723f?, 0x1bd9?}, 0x0?}})
\tgithub.com/parca-dev/parca-agent/pkg/runtime/python/python.go:627 +0x7ec
github.com/parca-dev/parca-agent/pkg/runtime/python.InterpreterInfo({0xc002718660?, {{0x24e723f?, 0x28?}, 0xe8?}})
\tgithub.com/parca-dev/parca-agent/pkg/runtime/python/python.go:648 +0x4b
github.com/parca-dev/parca-agent/pkg/runtime/interpreter.Fetch({0xc000000b40?, {{0x24e723f?, 0xc0009efe60?}, 0xc0?}})
\tgithub.com/parca-dev/parca-agent/pkg/runtime/interpreter/interpreter.go:43 +0x72
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).fetch(0xc000000b40, {0x2aaa568, 0xc0009efe60}, 0xddd, 0x0)
\tgithub.com/parca-dev/parca-agent/pkg/process/info.go:292 +0x7ec
github.com/parca-dev/parca-agent/pkg/process.(*InfoManager).Fetch(0xc000000b40, {0x2aaa568, 0xc002680090}, 0xc001507af8?)
\tgithub.com/parca-dev/parca-agent/pkg/process/info.go:214 +0x106
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).prefetchProcessInfo(0xc0024ba960, {0x2aaa568?, 0xc002680090?}, 0x2?)
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:490 +0x4b
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).addUnwindTableForProcess(0xc0024ba960, {0x2aaa568, 0xc002680090}, 0x2?)
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:568 +0x40c
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).onDemandUnwindInfoBatcher.func1({0xc00060a080, 0x2, 0x0?})
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:536 +0x5d
github.com/parca-dev/parca-agent/pkg/profiler/cpu.processEventBatcher({0x2aaa568, 0xc002680090}, 0xc0000e6840, 0xc000606fb8?, 0xc0014aff80)
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:619 +0x1ed
github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).onDemandUnwindInfoBatcher(0x0?, {0x2aaa568?, 0xc002680090?}, 0xc000b47e20?)
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:534 +0x57
created by github.com/parca-dev/parca-agent/pkg/profiler/cpu.(*CPU).Run in goroutine 243
\tgithub.com/parca-dev/parca-agent/pkg/profiler/cpu/cpu.go:857 +0x14a9
```

**Comment by kakkoyun** [comment]
@Ha-Dj Thanks for the reporting. I've taken the liberty to edit your issue a little bit. It seems like it's something concerning the python support. Do you try to profile Python workloads?

Also, could you proive me more information about your setup?

---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**


**To Reproduce**


**Expected behavior**


**Screenshots** or **Profiles** (using https://pprof.me)


**Logs**


**Software (please complete the following information):**
 - Parca Agent Version: [`parca-agent --version`]
 - Parca Server Version (if applicable): [`parca --version`]

**Workload (please complete the following information):**
- Runtime (if applicable):
- Compiler (if applicable):

**Environment (please complete the following information):**
- Linux Distribution: [`cat /etc/*-release`]
- Linux Version: [`uname -r`]
- Arch: [`uname -m`]
- Kubernetes Version (if applicable): [`kubectl --version`]
- Container Runtime (if applicable):

**Additional context**

**Comment by Ha-Dj** [comment]
<img width="975" alt="截屏2024-01-30 11 00 01" src="https://github.com/parca-dev/parca-agent/assets/70127179/33b6fcd6-fa75-4857-8c95-0ed5edc7c4d2">
<img width="975" alt="截屏2024-01-30 11 00 25" src="https://github.com/parca-dev/parca-agent/assets/70127179/eb0ee026-40c0-4dd3-b94c-d47786dcf430">
<img width="1255" alt="截屏2024-01-30 11 03 21" src="https://github.com/parca-dev/parca-agent/assets/70127179/908daba9-c771-4041-9413-e22ffa15f53f">
<img width="1353" alt="截屏2024-01-30 11 03 40" src="https://github.com/parca-dev/parca-agent/assets/70127179/dd886046-61be-479c-a186-34f017b99ed0">
<img width="1353" alt="截屏2024-01-30 11 03 44" src="https://github.com/parca-dev/parca-agent/assets/70127179/40bfe61b-bd58-41a0-a757-2988f19eaecd">

parca, version 0.20.0 (commit: d2b3947b351823a13da1b29757b4c8901e70e90c)
parca-agent, version 0.28.0 (commit: 1a09d0149d53f7e8c60287da7ada11b8ac29bf4d, date: 2023-12-04T14:09:50Z), arch: amd64

I'm following the quick start of binary.
The os tencentOS. The operating system is compatible with CentOS.

**Comment by Ha-Dj** [comment]
> @Ha-Dj Thanks for the reporting. I've taken the liberty to edit your issue a little bit. It seems like it's something concerning the python support. Do you try to profile Python workloads?
> 
> Also, could you proive me more information about your setup?
> 
> name: Bug report about: Create a report to help us improve title: '' labels: '' assignees: ''
> 
> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Screenshots** or **Profiles** (using https://pprof.me)
> 
> **Logs**
> 
> **Software (please complete the following information):**
> 
> * Parca Agent Version: [`parca-agent --version`]
> * Parca Server Version (if applicable): [`parca --version`]
> 
> **Workload (please complete the following information):**
> 
> * Runtime (if applicable):
> * Compiler (if applicable):
> 
> **Environment (please complete the following information):**
> 
> * Linux Distribution: [`cat /etc/*-release`]
> * Linux Version: [`uname -r`]
> * Arch: [`uname -m`]
> * Kubernetes Version (if applicable): [`kubectl --version`]
> * Container Runtime (if applicable):
> 
> **Additional context**

I think I haven't run any python program.
<img width="1353" alt="截屏2024-01-30 11 30 10" src="https://github.com/parca-dev/parca-agent/assets/70127179/baf6e8d8-c8e0-4655-930d-725b5bb7c266">

**Comment by kakkoyun** [comment]
@Ha-Dj Thanks a lot for the detailed report. This is helpful.

**Comment by kakkoyun** [comment]
Hey @Ha-Dj 👋 Could you please check with the latest binary/image after the fix?

You can find the images here https://github.com/parca-dev/parca-agent/pkgs/container/parca-agent
