### ISSUE TITLE
Metric to report on kthread and pid == 0 perf events

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#2478]
**Is your feature request related to a problem? Please describe.**

We're still investigating why it appears like we're dropping or not receiving perf events.

**Describe the solution you'd like**

Add another metric, similar to https://github.com/parca-dev/parca-agent/pull/2460, this time [before we start unwinding](https://github.com/parca-dev/parca-agent/blob/7a532053d10a220dc32362481f82487c80e55665/bpf/unwinders/native.bpf.c#L1144-L1154), and essentially for each "early return".

**Describe alternatives you've considered**

Nothing else I could think of other than add more observability.

**Additional context**

n/a

**Comment by gnurizen** [comment]
Closed by https://github.com/parca-dev/parca-agent/pull/2486
