### ISSUE TITLE
Incorrect cgrouppath for a pod

### ISSUE THREAD

**Issue by xiu** [parca-dev/parca-agent#268]
# Environment
-  `parca-agent` `0.5.0`
- `kernel` `5.10.61`
- `kubernetes` `1.21` with both cgroupv1 and cgroupv2 mounted
- `containerd` `1.4.9`

# What's happening
When looking into a pod using parca, we noticed that multiple processes were shown in the profile that are unrelated to each other.

<img width="1797" alt="Screenshot 2022-03-02 at 15 56 57" src="https://user-images.githubusercontent.com/666814/156392806-ddc0f81f-a37a-4ade-9cea-fe27e21671f8.png">

This is the target we used to see this result: http://localhost:7071/query?debug=1&query=%7Bcontainer%3D%22envoy-app%22%2C+containerid%3D%22docker%3A%2F%2F65e940dca4baa227bb0b3c1a91226c9717c0fbb5071df1c9f3ba04ab3a39152c%22%2C+namespace%3D%22app%22%2C+node%3D%22kube-worker2.x.y.z%22%2C+pod%3D%22app-864f4b66d6-gqfc2%22%7D

Digging a a bit more into it with @brancz, we noticed that `__cgroup_path__` was set to `/sys/fs/cgroup/perf_event` to all of them. This value is set in https://github.com/parca-dev/parca-agent/blob/1110c48ae92ff9c1a3eee622c278dae016a72173/pkg/k8s/k8s.go#L172-L188 and the struct always has the same values when called:
- `c.CgroupV1=""`
- `c.CgroupV2="/docker"`
- `c.Cgrouppath="/sys/fs/cgroup/unified/docker"`

Since this node has both cgroupv1 and cgroupv2 mounted, it might be related to #180.

# What's expected
The correct Cgrouppath is set and profiles only contain mappings for the requested pod.

**Comment by brancz** [comment]
Thank you so much for reporting this! Could you also share what container runtime is being used here?

**Comment by xiu** [comment]
Absolutely, we're using `containerd` `1.4.9`

**Comment by xiu** [comment]
I failed to mention that we're using openrc and not systemd on these workers. Looking into containerutils.GetCgroupPaths(), it seems that to match cgroupv1, we need to find `1:name=systemd:`, otherwise no cgroupv1 will be found.
https://github.com/parca-dev/parca-agent/blob/main/pkg/containerutils/containerutils.go#L117-L121

Here's is an example /proc/<pid>/cgroup in our case:
```
14:rdma:/
13:pids:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
12:hugetlb:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
11:net_prio:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
10:perf_event:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
9:net_cls:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
8:freezer:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
7:devices:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
6:memory:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
5:blkio:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
4:cpuacct:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
3:cpu:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
2:cpuset:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
1:name=openrc:/docker
0::/docker
```

On a node with `systemd`, we'd have the cgroup like:
```
1:name=systemd:/kubepods/burstable/pod1fa4240d-10d4-494f-88d2-80a639e26ac5/de86e0bfc1f648084db99ead71c756df43ec7e936342144c61d58961859a564b
```

For `name=openrc`, the value is still  `/docker`, which doesn't help us. We could pick the cgroup path from any of the other cgroups (`cpu`).

**Comment by xiu** [comment]
We ended up adding logic in GetCgroupPaths to handle this case:
```go
if strings.Contains(line, ":perf_events:") {
    cgroupPathV1 = strings.SplitN(line, ":", 3)[2]
    cgroupPathV1 = strings.TrimSuffix(cgroupPathV1, "\n")
    continue
}
```

This now returns the correct cgroup path for the pod. I'll push a PR once we tested it on the cluster.
