### ISSUE TITLE
Time-based invalidation of debug information caches

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#275]

**Comment by brancz** [comment]
Why time-based? I've always found size- or count-based to be more predictable for users in practice.

**Comment by kakkoyun** [comment]
I should have more specific. I specifically meant debug info exists response cache. Now that we have another way to find debug information, it would be more correct to invalidate local cache.

**Comment by brancz** [comment]
Ah, that makes perfect sense, yes! We probably have to also differentiate between the result of the response.
