### ISSUE TITLE
Remove usage of deprecated APIs

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#294]
```
libbpf: map 'counts' (legacy): legacy map definitions are deprecated, use BTF-defined maps instead
libbpf: map 'stack_traces' (legacy): legacy map definitions are deprecated, use BTF-defined maps instead
libbpf: Use of BPF_ANNOTATE_KV_PAIR is deprecated, use BTF-defined maps in .maps section instead
```

**Comment by kakkoyun** [comment]
Requires https://github.com/kubernetes/minikube/pull/12707 for testing (BTF is needed)

**Comment by v-thakkar** [comment]
If nobody is working on this, I can take this issue.

**Comment by kakkoyun** [comment]
Thanks @v-thakkar, that'd be great, actually!

**Comment by lilic** [comment]
@kakkoyun @v-thakkar Hi I am seeing this in the latest parca-agent, was this not maybe in release v0.9.0 of the agent?
```

libbpf: map 'stack_traces' (legacy): legacy map definitions are deprecated, use BTF-defined maps instead
libbpf: map 'counts' (legacy): legacy map definitions are deprecated, use BTF-defined maps instead
````

**Comment by v-thakkar** [comment]
Aya doesn't have the proper BTF support yet for their eBPF part. So we moved to use legacy map definitions since we started using Aya for our eBPF code. Reopening this so that we remember to fix it once BTF support is there is Aya. :)

**Comment by v-thakkar** [comment]
https://github.com/aya-rs/aya/issues/351

**Comment by kakkoyun** [comment]
Deprecated after https://github.com/parca-dev/parca-agent/pull/869
