### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#3]
Pretty complete eBPF ruby profiler that should be possible to be ported to Go: https://github.com/facebookexperimental/rbperf

**Comment by javierhonduco** [comment]
This is now done! 😉

**Comment by kakkoyun** [comment]
> This is now done! 😉

By @javierhonduco ❤️ 

<img src="https://media0.giphy.com/media/joeRYmOkLaj2U6hwdj/giphy.gif"/>
