### ISSUE TITLE
Basic e2e test setup

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#317]
We've had a couple of bugs by now that would have been caught by a simple e2e tests. The suggested setup for a test like this in CI:

* setup minikube
* setup parca
* setup parca-agent
* do a gRPC range query across all of time to ensure _some_ data is successfully returned

Once we have this setup we can extend it wit things like #190.

**Comment by v-thakkar** [comment]
One more thing to check:

- Pinned rust-nightly works on both x86 and arm64

**Comment by brancz** [comment]
(note I think that's a follow up, but one that depends on e2e tests being in place)
