### ISSUE TITLE
profiler: Add kernel feature checks at the startup

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca-agent#337]
See https://github.com/parca-dev/parca-agent/issues/333#issuecomment-1094997990

### ACs:

* [ ] Check necessary Linux features[BPF, BTF] of the host
* [ ] Check if Kernel stack unwinding enabled or not https://github.com/torvalds/linux/blob/master/arch/x86/Kconfig.debug#L252

**Comment by kakkoyun** [comment]
FYI https://github.com/parca-dev/parca-agent/issues/333#issuecomment-1096331904

**Comment by v-thakkar** [comment]
Oh nice, feature probes looks neat in that package.

**Comment by v-thakkar** [comment]
Libbpfgo has all the helpers we need for this (and more) :) https://github.com/aquasecurity/libbpfgo/tree/64458ba5a32013dda2d4f88838dde8456922333d/helpers
https://github.com/aquasecurity/libbpfgo/blob/64458ba5a32013dda2d4f88838dde8456922333d/docs/helpers.md

**Comment by v-thakkar** [comment]
JFYI, we're working on having our in-house kconfig package for the checks.

**Comment by kakkoyun** [comment]
Sorry for the noise on this issue. Apparently, the new projects feature does weird thing on issues :sweat_smile:
