### ISSUE TITLE
optimization: Optimization after v0.8.0

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#393]
This is how it looks after running the agent for 3 hours. I have added an interactive profile version and possible optimization areas with screenshots.

If anyone is interested, optimization games for parca-agent begins :stuck_out_tongue: 

Interactive version: https://share.polarsignals.com/8836b8d/

* Write Profile:
![Thu May  5 03:47:22 PM CEST 2022](https://user-images.githubusercontent.com/536449/166938412-5116f826-4dd6-4afc-8b65-6c1059bcbb45.png)

![Thu May  5 03:49:33 PM CEST 2022](https://user-images.githubusercontent.com/536449/166938667-3a8319b8-6ef3-4a92-89c3-3efc5c4a6e58.png)

* Build Profile:
![Thu May  5 03:48:05 PM CEST 2022](https://user-images.githubusercontent.com/536449/166938504-76155855-6cec-4110-a6b8-7621af670421.png)

* Ensure Uploaded:
![Thu May  5 03:48:36 PM CEST 2022](https://user-images.githubusercontent.com/536449/166938566-a52e7801-28df-4749-9e5b-ce1d3fbd9d24.png)

**Comment by kakkoyun** [comment]
Related #391 

kysm is not the biggest bottleneck we have right now.

cc @javierhonduco

**Comment by javierhonduco** [comment]
Thanks for doing this!

The unknown frames seem odd, let's investigate what it is and why it can't symbolise
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/959128/166965120-f31feae1-b788-40e6-b28a-8c54907a16d8.png">

**Comment by kakkoyun** [comment]
Deprecated.
