### ISSUE TITLE
Extended Go support

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#4]
I've only done a light investigation on this, so this may still be bogus.

Elf symbols (`.symtab`) are often stripped using `-ldflags="-s -w"`, but the `.gosymtab` elf section is almost always there, ideally we convert `.gosymtab` to a “normal” elf debug symbol table (`.symtab`), if it's not already the same, and upload that as debug info as if they had been there the entire time.

Edit: According to [this](https://www.mail-archive.com/golang-nuts@googlegroups.com/msg40112.html) email thread .gosymtab is empty and the content of `.gopclntab` is what we should be able to use.

**Comment by kakkoyun** [comment]
Done, except #292
