### ISSUE TITLE
chore: Rename SystemD discovery to Cgroups

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#400]
The current SystemD discovery mechanism in reality works on bare Cgroups. The name can be confusing, and I believe it's not accurate. Please correct me if I'm wrong :)

- [x] Add renamed flags, without removing the new ones. Mark the old ones as deprecated, and update the README (https://github.com/parca-dev/parca-agent/pull/401)
- [ ] Update the names in `pkg/discovery`
- [ ] Update the separate docs
- [ ] Some versions from now, let's remove the current SystemD flag

**Comment by kakkoyun** [comment]
@javierhonduco shall we close this one?

**Comment by javierhonduco** [comment]
Yes!! Good shout!
