### ISSUE TITLE
Errors on default installation on Linode managed Kubernetes (K8s version 1.23)

### ISSUE THREAD

**Issue by onprem** [parca-dev/parca-agent#416]
I was going through the [getting started on Kubernetes guide](https://www.parca.dev/docs/kubernetes) for getting a Parca install up and running on managed Kubernetes by Linode, but `parca-agent` didn't scrape any profiles and I got these errors in the logs.

```l
level=warn ts=2022-05-19T10:58:22.893573552Z caller=profiler_pool.go:156 msg="profiler ended with error" error="open cgroup: open /sys/fs/cgroup/perf_event/: no such file or directory" labels="{__name__=\"parca_agent_cpu\", app_kubernetes_io_component=\"exporter\", app_kubernetes_io_name=\"blackbox-exporter\", app_kubernetes_io_part_of=\"kube-prometheus\", app_kubernetes_io_version=\"0.20.0\", container=\"kube-rbac-proxy\", containerid=\"docker://5b750380cfb292366cb164b9075c23d549f223f08722ac941f85523522c29958\", namespace=\"monitoring\", node=\"lke61338-95353-62860e1f0133\", pod=\"blackbox-exporter-6dfcb55b88-8jdgg\", pod_template_hash=\"6dfcb55b88\"}"
```

Upon looking in the `/sys/fs/cgroup` directory, I didn't find the `perf_event` controller there.

```
$ kubectl exec parca-agent-7pzst -- ls /sys/fs/cgroup/
-.mount
cgroup.controllers
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cpu.pressure
cpu.stat
cpuset.cpus.effective
cpuset.mems.effective
dev-hugepages.mount
dev-mqueue.mount
init.scope
io.cost.model
io.cost.qos
io.pressure
io.stat
kubepods
memory.numa_stat
memory.pressure
memory.stat
sys-fs-fuse-connections.mount
sys-kernel-config.mount
sys-kernel-debug.mount
sys-kernel-tracing.mount
system.slice
user.slice
```

I confirmed that both cgroup v1 and v2 are available.

```
$ kubectl exec parca-agent-7pzst -- grep cgroup /proc/filesystems
nodev    cgroup
nodev    cgroup2
```

### workaround

Manually mounting the `perf_event` controller on each node worked.
```
# mkdir /sys/fs/cgroup/perf_event
# mount -t cgroup -o perf_event none /sys/fs/cgroup/perf_event
```

The environment was Kubernetes version 1.23, which is still running `dockershim` as the container runtime, maybe this was the reason that `perf_controller` was missing by default.

**Comment by brancz** [comment]
Marking this as an enhancement as I think the parca-agent should setup the perf events controller if it's not already there. Thank you so much for opening this and all of the details! 🎉

**Comment by myaser** [comment]
thank you for raising the issue and finding the workaround. I was running through the same problem

**Comment by javierhonduco** [comment]
Hi!!

We have completely removed the reliance on the profiler on the cgroups hierarchy after https://github.com/parca-dev/parca-agent/pull/627, which should help with this issue.

If you can try the current `main` that would be great, otherwise, we should be releasing the updated Agent with system-wide enabled in ~2-3 weeks.

Feel free to re-open if things are still broken for you!

cc @kakkoyun
