### ISSUE TITLE
symbolizer: In some occasions we are uploading broken debug files

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#420]
Seems like some of the debug files we are uploading to Parca are either empty or wrong. Opening this issue so I don't forget to take a closer look at it. 

> ```level=error name=parca ts=2022-05-26T10:17:06.842259165Z caller=symbolizer.go:59 component=symbolizer msg="symbolization attempt finished with errors" err="2 errors occurred:\n\t* storage symbolization request failed: failed to check for DWARF: failed to open elf: bad magic number '[0 0 0 0]' in record at byte 0x0\n\t* storage symbolization request failed: failed to check for DWARF: failed to open elf: bad magic number '[0 0 0 0]' in record at byte 0x0\n\n"```

**Comment by kakkoyun** [comment]
Probably better to move this issue to the server-side. It seems like we send badly formated files to the server-side.

**Comment by javierhonduco** [comment]
Let me open another issue in the backend, as I don't think we should be sending nor accepting broken debug files

**Comment by brancz** [comment]
Agreed, the server should validate, but the client shouldn't even attempt to upload faulty data.
