### ISSUE TITLE
client: RPC message too big

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#421]
Just so I don't forget to look into this. I've occasionally stumbled upon this error

> ```level=debug ts=2022-05-25T09:42:00.90387003Z caller=write_client.go:92 msg="batch write client failed to send profiles" retry=2.604991381s count=1 err="rpc error: code = Internal desc = failed to normalize pprof: Key with size 96032 exceeded 65000 limit. Key:\n00000000[...]"```

**Comment by kakkoyun** [comment]
Possible duplicate https://github.com/parca-dev/parca-agent/issues/203

**Comment by heylongdacoder** [comment]
I did some troubleshooting on this issue and I think the error message is come from the `badger`. This line of code(https://github.com/dgraph-io/badger/blob/master/txn.go#L357) match the error message above. Let me study how to fix this.

**Comment by heylongdacoder** [comment]
I think this issue is fixed by https://github.com/parca-dev/parca/pull/1178. Since this PR introduce some hashing to reduce the length of key.

**Comment by javierhonduco** [comment]
@kakkoyun sounds good to me! Closing it, let's keep an eye just in case it happens again
