### ISSUE TITLE
chore: Reduce the time spent in CI checks

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#460]
Similar to https://github.com/parca-dev/parca/issues/1152, we could reduce the time we spent in CI.

We should cross-build the binaries and copy them to the containers. We have already reduced the external dependencies to zero and statically linked the binaries.

The only challenge I foresee is to be able to cross-compile libbpf with CGO.

Keep in mind that we can't break the reproducible build guarantee.

xref: https://github.com/parca-dev/parca/pull/1153

**Comment by maxbrunet** [comment]
Talked about in https://github.com/parca-dev/parca-agent/pull/465#discussion_r898725845, we can run multi-stage container build with different architecture with Buildkit:
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

Here is a short example (Docker Buildx is used there): https://github.com/maxbrunet/prometheus-elasticache-sd/blob/v1.0.41/Dockerfile

Podman seems to support the `TARGET*` args too, but not `BUILD*`:
https://github.com/containers/buildah/blob/v1.26.1/imagebuildah/build.go#L349-L381

Not sure if that would help yet, but Podman can be used with Buildkit: https://pythonspeed.com/articles/podman-buildkit/

**Comment by maxbrunet** [comment]
Made a test, all ARGs are available with Podman:

<details>
<summary><code>Dockerfile</code></summary>

```Dockerfile
FROM --platform="${BUILDPLATFORM}" docker.io/busybox

ARG TARGETPLATFORM \
    TARGETOS \
    TARGETARCH \
    TARGETVARIANT \
    BUILDPLATFORM \
    BUILDOS \
    BUILDARCH \
    BUILDVARIANT

RUN printf 'TARGETPLATFORM: %s\n' "${TARGETPLATFORM}" && \
    printf 'TARGETOS: %s\n' "${TARGETOS}" && \
    printf 'TARGETARCH: %s\n' "${TARGETARCH}" && \
    printf 'TARGETVARIANT: %s\n' "${TARGETVARIANT}" && \
    printf 'BUILDPLATFORM: %s\n' "${BUILDPLATFORM}" && \
    printf 'BUILDOS: %s\n' "${BUILDOS}" && \
    printf 'BUILDARCH: %s\n' "${BUILDARCH}" && \
    printf 'BUILDVARIANT: %s\n' "${BUILDVARIANT}"
```

</details>

```console
$ podman build --platform linux/arm64 .
time="2022-06-16T09:37:27-07:00" level=warning msg="missing \"TARGETPLATFORM\" build argument. Try adding \"--build-arg TARGETPLATFORM=<VALUE>\" to the command line"
STEP 1/3: FROM docker.io/busybox
STEP 2/3: ARG TARGETPLATFORM     TARGETOS     TARGETARCH     TARGETVARIANT     BUILDPLATFORM     BUILDOS     BUILDARCH     BUILDVARIANT
--> 356b9da472c
STEP 3/3: RUN printf 'TARGETPLATFORM: %s\n' "${TARGETPLATFORM}" &&     printf 'TARGETOS: %s\n' "${TARGETOS}" &&     printf 'TARGETARCH: %s\n' "${TARGETARCH}" &&     printf 'TARGETVARIANT: %s\n' "${TARGETVARIANT}" &&     printf 'BUILDPLATFORM: %s\n' "${BUILDPLATFORM}" &&     printf 'BUILDOS: %s\n' "${BUILDOS}" &&     printf 'BUILDARCH: %s\n' "${BUILDARCH}" &&     printf 'BUILDVARIANT: %s\n' "${BUILDVARIANT}"
TARGETPLATFORM: linux/arm64
TARGETOS: linux
TARGETARCH: arm64
TARGETVARIANT: 
BUILDPLATFORM: linux/amd64
BUILDOS: linux
BUILDARCH: amd64
BUILDVARIANT: 
COMMIT
--> 0f1b3c41dce
[Warning] one or more build args were not consumed: [TARGETARCH TARGETOS]
0f1b3c41dce4dd3420f2807a94266764892b17c519d341ecd5fcb465ce394313
```

It warns about `--build-arg` being missing, but it's all good. And `--platform` needs to be used, instead of `--arch`.

**Comment by maxbrunet** [comment]
The only thing left seems to be figuring out how to pass `clang`'s `--target` arg down the Makefile chain to build bpf. I'll look into it and open a PR

**Comment by kakkoyun** [comment]
FWIW `clang` isn't used to build BPF programs anymore. We only use it to build `libbpf` which is necessary for `libbpf-go` that we use in the user space. 

If it's easier, we can check out how to efficiently cross-compile CGO programs and we can copy binaries into the containers.

**Comment by kakkoyun** [comment]
And @maxbrunet needless to say, amazing job!! I'm grateful that you're taking care of this!

**Comment by maxbrunet** [comment]
> FWIW `clang` isn't used to build BPF programs anymore. We only use it to build `libbpf` which is necessary for `libbpf-go` that we use in the user space.

I know the BPF program is built by the `xtask`, but isn't libbpf built with `clang` here?:

https://github.com/parca-dev/parca-agent/blob/05617ec399184c5825cdbcd99eacfa63fd6ae73a/Makefile#L115-L116

**Comment by kakkoyun** [comment]
> > FWIW `clang` isn't used to build BPF programs anymore. We only use it to build `libbpf` which is necessary for `libbpf-go` that we use in the user space.
> 
> I know the BPF program is built by the `xtask`, but isn't libbpf built with `clang` here?:
> 
> https://github.com/parca-dev/parca-agent/blob/05617ec399184c5825cdbcd99eacfa63fd6ae73a/Makefile#L115-L116

Yes, exactly. I was just being pedantic for other readers to point out that's exactly needed for `libbpf` :)
