### ISSUE TITLE
chore: Improve container build script

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca-agent#462]
At the moment container build script doesn't fail when arm64 build fails to pass. We should add a check there so that we can continue to have arm images.

**Comment by kakkoyun** [comment]
I thought this PR https://github.com/parca-dev/parca-agent/pull/440 should have fixed it, hasn't it?

**Comment by v-thakkar** [comment]
That fix only seems to be helping with it partially. This is why I had to check manually even though. Until yesterday's fix arm build was failing with below error in CI but all checks were showing green for the PRs sent between these fixes:

```
error: failed to run custom build command for `llvm-sys v140.0.2`
Caused by:
  process didn't exit successfully: `/tmp/cargo-install3vFWnH/release/build/llvm-sys-ab6cf1e2b1c2bf54/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_SYS_140_PREFIX
  cargo:rerun-if-env-changed=LLVM_SYS_140_IGNORE_BLOCKLIST
  cargo:rerun-if-env-changed=LLVM_SYS_140_STRICT_VERSIONING
  cargo:rerun-if-env-changed=LLVM_SYS_140_NO_CLEAN_CFLAGS
  cargo:rerun-if-env-changed=LLVM_SYS_140_USE_DEBUG_MSVCRT
  cargo:rerun-if-env-changed=LLVM_SYS_140_FFI_WORKAROUND
  --- stderr
  thread 'main' panicked at 'Could not determine LLVM version from llvm-config.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-140.0.2/build.rs:229:10
```
Also, I was only able to reproduce above error with `docker buildx build --platform linux/arm64` on amd64 machine and not with `make container` for some reason.

**Comment by maxbrunet** [comment]
Found the issue, there is a `+` instead `-` which turn off the flags:

https://github.com/parca-dev/parca-agent/blob/3d97faa55e2532dc37e5b3ba5a3f2f2f49fd8439/make-containers.sh#L2

Going open a PR with the fix and a thorough linting of the container build

**Comment by v-thakkar** [comment]
Oops, yes. You're right! :see_no_evil:

**Comment by v-thakkar** [comment]
I think parca has a similar script too. If you fancy sending a PR there as well @maxbrunet. Thanks :)

**Comment by maxbrunet** [comment]
> I think parca has a similar script too. If you fancy sending a PR there as well @maxbrunet. Thanks :)

I'll have a look once #465 is reviewed and merged :+1:
