### ISSUE TITLE
chore: Use Renovate where Dependabot falls short

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#469]
> And I'll check out Renovate!

You can find examples of how I use it in my personal repos:
https://github.com/maxbrunet/bitbucket-semantic-pull-requests
https://github.com/maxbrunet/prometheus-elasticache-sd

They maintain themselves

_Originally posted by @maxbrunet in https://github.com/parca-dev/parca-agent/issues/465#issuecomment-1157821734_

**Comment by maxbrunet** [comment]
Done in #484
