### ISSUE TITLE
chore: Use distroless base images

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#496]
https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md

We can use distroless images as base and we can simplify our build docker build stages. What do you think?

For the ones who don't have context, in practice, we can remove the following and their dependencies from our docker builds:
 https://github.com/parca-dev/parca-agent/blob/ba3b7410f79a7820c58b9b66c200a5bbe82474b5/Dockerfile#L65-L67

**Comment by brancz** [comment]
sounds good to me
