### ISSUE TITLE
local-development: BPF code isn't rebuilt when running `make build-dyn`

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#506]
Unfortunately `make build-dyn` doesn't rebuild the BPF code `make build` seems to work, but I haven't fully verified this

**Comment by kakkoyun** [comment]
Is this still valid after the recent changes?

**Comment by javierhonduco** [comment]
Unfortunately, it doesn't seem to fix it. I can repro this with:

```shell
$ make clean
$ make build-dyn
$ echo "____" >>  bpf/cpu-profiler/src/main.rs 
$ make build-dyn # <- I would have expected this to fail, but the BPF code isn't rebuilt
```
