### ISSUE TITLE
ci: Require status checks before merging

### ISSUE THREAD

**Issue by maxbrunet** [parca-dev/parca-agent#509]
Renovate has been able to auto-merge PR #502 which was failing the CI, it may the reason why `main` is failing now, checks should be required in the branch protection rule:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

Repository administrator will still be able to bypass them if "include administrators" is left uncheck.

cc @kakkoyun

**Comment by kakkoyun** [comment]
![Mon Jun 27 08:19:32 AM CEST 2022](https://user-images.githubusercontent.com/536449/175872581-ea1255df-0bd6-4902-904a-75842d03a80a.png)

I have enabled the strict mode for the checks.

**Comment by maxbrunet** [comment]
@kakkoyun PR are still merged without waiting for any checks (e.g #514), although the box is checked, there are no required checks at the moment, you must "Choose which [status checks](https://docs.github.com/rest/commits/statuses) must pass", for example:

![image](https://user-images.githubusercontent.com/32458727/176265794-9ecfaf5f-839a-420d-9f41-7e275421ca6f.png)

After that, the checks will show with a "Required" label:

![image](https://user-images.githubusercontent.com/32458727/176267837-7f603834-1c78-4a89-979b-9d24ca31a040.png)

**Comment by kakkoyun** [comment]
Thanks, @maxbrunet for the screenshots. It helped a lot :) I have marked certain tasks as required.

**Comment by kakkoyun** [comment]
> It seems the `paths` option is causing troubles with required checks, maybe we should replaced it with an action, so the workflows always trigger, but do not actually run, what do you think?
> 
> https://github.com/marketplace/actions/skip-duplicate-actions#skip-if-paths-not-changed

If it works, I'm totally in for this. I had to disable some checks because of this.
