### ISSUE TITLE
bpf: Make sure there is no concurrent access issue with CPU profiler

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#520]
By migrating to Rust, we might introduce a regression for atomic counters.
The easier way to fix the issue is to use pre-CPU BPF maps.

xref: https://github.com/aquasecurity/libbpfgo/pull/156/files

**Comment by maxbrunet** [comment]
Would it be as simple as `sed -i 's/HashMap/PerCpuHashMap/g' bpf/cpu-profiler/src/main.rs`?:

```diff
--- a/bpf/cpu-profiler/src/main.rs
+++ b/bpf/cpu-profiler/src/main.rs
@@ -8,7 +8,7 @@ pub static LICENSE: [u8; 4] = *b"GPL\0";
 use aya_bpf::{
     bindings::BPF_F_USER_STACK,
     macros::{map, perf_event},
-    maps::{HashMap, StackTrace},
+    maps::{PerCpuHashMap, StackTrace},
     programs::PerfEventContext,
     BpfContext,
 };
@@ -24,8 +24,8 @@ pub struct StackCountKey {
 }
 
 #[map(name = "counts")]
-pub static mut COUNTS: HashMap<StackCountKey, u64> =
-    HashMap::with_max_entries(MAX_STACK_ADDRESSES, 0);
+pub static mut COUNTS: PerCpuHashMap<StackCountKey, u64> =
+    PerCpuHashMap::with_max_entries(MAX_STACK_ADDRESSES, 0);
 
 #[map(name = "stack_traces")]
 pub static mut STACK_TRACES: StackTrace = StackTrace::with_max_entries(MAX_STACK_DEPTH, 0);
```

The maps are still named `counts`, so I guess the agent would pick them up without change:

https://github.com/parca-dev/parca-agent/blob/1e7edd6629ffd4b2ddf5fdb5ed10bf42c5279121/pkg/profiler/profiler.go#L378

That builds and at first look seem to work

**Comment by kakkoyun** [comment]
@maxbrunet This seems about right. As you suggested we need to test this extensively.

And I'd suggest we have the `libbpf-go` and `libbpf` upgrade in a separate PR. We can also automate upgrades. Previously it was disabled because of the lack of tests. (We now have them https://github.com/parca-dev/parca-agent/blob/main/pkg/profiler/profiler_test.go) We should test our access patterns.

I think this is on the right track. Looking forward to the PR :hugs:

**Comment by kakkoyun** [comment]
> (untested, I have not been able to build libbpf v0.8 so far, compilation errors on `usdt.c`)

This could be happening because we need to upgrade the submodule in https://github.com/parca-dev/parca-agent/tree/main/3rdparty separately to the v0.8.0 tag. A simple Go module upgrade won't be enough.

**Comment by maxbrunet** [comment]
> > (untested, I have not been able to build libbpf v0.8 so far, compilation errors on `usdt.c`)
> 
> This could be happening because we need to upgrade the submodule in [https://github.com/parca-dev/parca-agent/tree/main/3rdparty](https://github.com/parca-dev/parca-agent/tree/main/3rdparty?rgh-link-date=2022-06-30T06%3A27%3A19Z) separately to the v0.8.0 tag. A simple Go module upgrade won't be enough.

Yes, it is what I was at, v0.8 now requires `pkg-config` and `usdt.c` does not compile, maybe there is another new requirement I am missing or something I do not clean up properly (I did `rm -rf dist/` and nothing obvious with a dry-run of `git clean` )

<details>
<summary>CC errors</summary>

```
  CC       /home/maxime/Documents/github.com/maxbrunet/parca-agent/dist/libbpf/staticobjs/usdt.o
usdt.c:562:28: error: unknown type name ‘GElf_Nhdr’; did you mean ‘GElf_Shdr’?
  562 |                            GElf_Nhdr *nhdr, const char *data, size_t name_off, size_t desc_off,
      |                            ^~~~~~~~~
      |                            GElf_Shdr
usdt.c: In function ‘collect_usdt_targets’:
usdt.c:578:9: error: unknown type name ‘GElf_Nhdr’; did you mean ‘GElf_Shdr’?
  578 |         GElf_Nhdr nhdr;
      |         ^~~~~~~~~
      |         GElf_Shdr
usdt.c:610:23: error: implicit declaration of function ‘gelf_getnote’; did you mean ‘gelf_getsym’? [-Werror=implicit-function-declaration]
  610 |         while ((off = gelf_getnote(data, off, &nhdr, &name_off, &desc_off)) > 0) {
      |                       ^~~~~~~~~~~~
      |                       gelf_getsym
usdt.c:616:23: error: implicit declaration of function ‘parse_usdt_note’; did you mean ‘parse_usdt_spec’? [-Werror=implicit-function-declaration]
  616 |                 err = parse_usdt_note(elf, path, base_addr, &nhdr,
      |                       ^~~~~~~~~~~~~~~
      |                       parse_usdt_spec
usdt.c: At top level:
usdt.c:1093:28: error: unknown type name ‘GElf_Nhdr’; did you mean ‘GElf_Shdr’?
 1093 |                            GElf_Nhdr *nhdr, const char *data, size_t name_off, size_t desc_off,
      |                            ^~~~~~~~~
      |                            GElf_Shdr
cc1: all warnings being treated as errors
```

</details>

**Comment by maxbrunet** [comment]
> (untested, I have not been able to build libbpf v0.8 so far, compilation errors on `usdt.c`)

Fixed this, wrong ELF lib in `nix-shell`

**Comment by javierhonduco** [comment]
Hey Maxime, thanks for chipping in! 

Your approach would definitely work, but I am a bit concerned about changing the memory usage and time we need to process from O(1) to O(cpu_count) as well as increasing the userspace code complexity, as we would have to perform the merge of the stack counts in userspace.

Let me try to see if we could bring the atomics back, as I would be more comfortable shipping this approach!

**Comment by kakkoyun** [comment]
@maxbrunet But it's close to the finish line, please don't refrain to open the PR. We can benchmark them. I think we should do this comparison anyway.

**Comment by maxbrunet** [comment]
> Your approach would definitely work, but I am a bit concerned about changing the memory usage and time we need to process from O(1) to O(cpu_count) as well as increasing the userspace code complexity, as we would have to perform the merge of the stack counts in userspace.
> 
> Let me try to see if we could bring the atomics back, as I would be more comfortable shipping this approach!

I definitely agree, quickly looking around we may be able to use BPF ring buffer:
https://www.kernel.org/doc/html/latest/bpf/ringbuf.html
https://nakryiko.com/posts/bpf-ringbuf/

It requires Linux 5.8 (torvalds/linux@457f44363a8894135c85b7a9afd2bd8196db24ab) and Aya does not have support for it yet (aya-rs/aya#12).
Let me know if you have anything else in mind.

Since it is a regression, how was it implemented before?

For reference, here is the last revision of the [old clang program](https://github.com/parca-dev/parca-agent/blob/f2e1871d845f8fed2a36a667e6fd030cdbbb9cf0/parca-agent.bpf.c).

> @maxbrunet But if it's close to the finish line, please don't refrain to open the PR. We can benchmark them. I think we should do this comparison anyway.

Sure, the above should pretty much be it, it would create conflicts with #532 though

**Comment by kakkoyun** [comment]
> I definitely agree, quickly looking around we may be able to use BPF ring buffer:
> https://www.kernel.org/doc/html/latest/bpf/ringbuf.html
> https://nakryiko.com/posts/bpf-ringbuf/

We deliberately don't want to use ring buffers. Since it's a sampling profiler, it's more efficient to aggregate samples and then sync them when they are actually needed.

> Since it is a regression, how was it implemented before?

We were using atomic increments. We deliberately drop them because of the lack of support in Aya back then.
https://github.com/parca-dev/parca-agent/blob/f2e1871d845f8fed2a36a667e6fd030cdbbb9cf0/parca-agent.bpf.c#L136-L137

I actually tried this in Rust but in the review process (not in GitHub, probably Discord), it pointed to me that this wouldn't work. I don't remember specifics to be honest.

https://github.com/parca-dev/parca-agent/pull/377/commits/895efb40589ebf7ee61b3378c5f29acf613c1ee0

cc @javierhonduco 

> Sure, the above should pretty much be it, it would create conflicts with #532 though

#532 has a lot of ways to go, it won't land in v0.9.0

**Comment by javierhonduco** [comment]
Just as an update, I am still testing the lock approach, so far the code generation seems... not what I expected, as the lock instruction is not there. I suspect that the BPF backend in rustc might not support it.

Will post the code and any updates I might have in a bit

**Comment by javierhonduco** [comment]
Hi folks, sorry for the delay! This is the current state of experiments for locking, as Kemal mentioned we used to use both the `__sync_fetch_and_add` intrinsic as well as `bpf_map_lookup_or_try_init`:

https://github.com/parca-dev/parca-agent/blob/f2e1871d845f8fed2a36a667e6fd030cdbbb9cf0/parca-agent.bpf.c#L132  

I've tried to bring both back to ensure that we remove the new data race that was introduced in the Rust port, as well as trying to keep the behaviour as closely as possible to the previous one we had without incurring in higher CPU or memory usage in Parca Agent's userspace components.

You can find the changes in Parca Agent (https://github.com/javierhonduco/parca-agent/commit/5b3b694766340934ca85ace80a80aab969e6348c) as well as the changes in aya (https://github.com/javierhonduco/aya/commit/351529737a0b84f05f083c32205024e01227a1af) for this to work.

In order to verify that the generated code is correct, I've taken a look a the JIT'ed x86:
```
$ sudo bpftool prog dump jited id 3347
```
and:

1. Made sure that we are incrementing by 1 atomically (comments mine)
```
[...]
# sets .bx to 1 
  80:   mov    $0x1,%ebx  
  85:   mov    %rbx,-0x8(%rbp)
  89:   mov    %rbp,%rsi
  8c:   add    $0xffffffffffffffe8,%rsi
  90:   mov    %rbp,%rdx
  93:   add    $0xfffffffffffffff8,%rdx
  97:   movabs $0xffff8a5b0cba1000,%rdi
  a1:   call   0xffffffffcb286a08
  a6:   test   %rax,%rax
  a9:   je     0x00000000000000af
  ab:   add    $0x40,%rax
  af:   test   %rax,%rax
  b2:   je     0x00000000000000b9
# atomically access rax's pointee, and increment it by .bx which is 1
  b4:   lock add %rbx,0x0(%rax) 
  b9:   xor    %eax,%eax
  bb:   pop    %r13
  bd:   pop    %rbx
  be:   leave  
  bf:   ret    
```

And comparing the instructions of the code from my branch replacing the intrinsic with a normal increment:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/959128/177357052-0af65f73-abdf-4060-bf26-6fd4c2746c16.png">

Please take a look and let me know what you think!
