### ISSUE TITLE
build: Simplify the eBPF artifact build process

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca-agent#547]
Let's get rid of makefile under bpf/. We should be able to handle everything for the rust code via Cargo and Makefile at the root of the project should have bpf/setup, bpf/build with Cargo commands. 
- [ ] Remove Makefile in bpf/
- [ ] Add setup and build options in root Makefile
- [ ] Add a way to install bpf-linker based on arch:
- For x86: cargo install bpf-linker
- For arm64: LLVM_SYS_140_PREFIX=/usr/lib/llvm-14 cargo install --git https://github.com/aya-rs/bpf-linker --tag $(BPF_LINKER_VERSION) --no-default-features --features system-llvm -- bpf-linker

**Comment by kakkoyun** [comment]
Deprecated after https://github.com/parca-dev/parca-agent/pull/869
