### ISSUE TITLE
elfwriter: Compress DWARF sections by default

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#578]

**Comment by javierhonduco** [comment]
This would be a great feature! Wondering if we should implement this in the server or in the agent (or in both, and allow opt-in/out in the agent).

I believe it would be a matter of the tradeoff we choose: network (uncompressed) vs CPU (incurred when compression)

**Comment by brancz** [comment]
since these uploads should only ever occur once for a given binary I think the CPU cost is not actually worth the reduction in network traffic

**Comment by kakkoyun** [comment]
> since these uploads should only ever occur once for a given binary I think the CPU cost is not actually worth the reduction in network traffic

A very good argument actually. This could be a premature optimisation.
