### ISSUE TITLE
ci: Add Darwin binaries of `parca-agent` to the release assets

### ISSUE THREAD

**Issue by manojVivek** [parca-dev/parca-agent#608]
Currently, we are only publishing Linux binaries as release assets, having Mac binaries there would be useful to try out the `scraping` mode.

**Comment by brancz** [comment]
This issue should be on parca, not the parca-agent. The agent will always only work on Linux since it uses eBPF. The server is what does the scraping.

**Comment by kakkoyun** [comment]
> The agent will always only work on Linux since it uses eBPF.

:100: Until the day Apple decides to put eBPF on Darwin (Microsoft is working on it).

Closing this.

**Comment by akram** [comment]
> > The agent will always only work on Linux since it uses eBPF.
> 
> 💯 Until the day Apple decides to put eBPF on Darwin (Microsoft is working on it).
> 
> Closing this.

@kakkoyun what do you think about this article https://medium.com/@harry-touloupas/when-mac-m1-m2-met-ebpf-a-tale-of-compatibility-6b9a6bc53f3e ?

Would it open the door to parca-agent on Mac ?

**Comment by brancz** [comment]
That guide sets up a Linux VM, so it’s still just a linux binary.
