### ISSUE TITLE
debuginfo: Synthesize ORC information

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#619]

**Comment by javierhonduco** [comment]
The kernel unwinding mechanism is transparent to us. We don't have to generate the ORC information, nor check for it when using the perf_event_open syscall (or BPF get_stack_id) helpers, which AFAIK use the same mechanisms

**Comment by kakkoyun** [comment]
I should have clarified more. The idea behind this one was to generate ORC information for the user processes that don't have any unwind information and let the kernel do the unwinding or implement a custom ORC unwinding in eBPF space to the same for user programs since the ORC-based unwinding is simpler to implement.

We can open re-evaluate and open an issue about this when we know more about the space.

**Comment by javierhonduco** [comment]
I see! Should we then merge it with https://github.com/parca-dev/parca-agent/issues/618? In the end the difference is what's the format we choose, being ORC's, or a custom one, no?

**Comment by kakkoyun** [comment]
> I see! Should we then merge it with #618? In the end the difference is what's the format we choose, being ORC's, or a custom one, no?

Sounds good to me!
