### ISSUE TITLE
system-wide: Cleanups and further work

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#629]
After we land https://github.com/parca-dev/parca-agent/pull/627, there will be some outstanding work:

- [x] https://github.com/parca-dev/parca-agent/issues/631 (Fixed by https://github.com/parca-dev/parca-agent/pull/641)
- [x] https://github.com/parca-dev/parca-agent/issues/635 (Fixed by https://github.com/parca-dev/parca-agent/pull/641)
- [x] Run the new setup in minikube for several hours (already ran for 1h or so without problems)
- [x] Update readme, cli usage, etc (https://github.com/parca-dev/parca-agent/issues/650)
- [x] Maybe add the systemd/cgroup metadata (https://github.com/parca-dev/parca-agent/pull/651)
- [x] Test in demo cluster
- [x] Remove unneeded code
- [x] Tackle the TODOs in the code
- ~~Decide on the Agent's web UI features / troubleshooting helpers (e.g. pprof generation)~~ https://github.com/parca-dev/parca-agent/issues/691
- [x] Create issue for UI's filtering with lots of data
- [x] Ensure that all the local testing scripts work fine
- [x] Update the design document (https://github.com/parca-dev/parca-agent/issues/650)

Before and in the release:
- [ ] Update documentation

(Will create independent issues for some of these tasks)

**Comment by kakkoyun** [comment]
I will be addressing several issues on #663
