### ISSUE TITLE
minikube: Add clang-with-fp container

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#630]
It would be wonderful to have the [clang-with-fp ](https://github.com/parca-dev/parca-demo/tree/main/cpp)test container to minikube

**Comment by javierhonduco** [comment]
@kakkoyun happy to close this issue, we mostly test this in Demo / our local machines, and perhaps this is better suited in non-minikube integration tests, what do you think?

**Comment by kakkoyun** [comment]
> @kakkoyun happy to close this issue, we mostly test this in Demo / our local machines, and perhaps this is better suited in non-minikube integration tests, what do you think?

👍
