### ISSUE TITLE
stack quality: Investigate too few? profiles for Parca

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#631]
After running for 30 minutes and running multiple queries, I expected more stack traces:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/959128/181524937-9a88edd4-f879-453c-a2db-3afa718308be.png">

**Comment by brancz** [comment]
what is `30'`? 30 second? 30 minutes? 30s would not seem very unusual, we optimized Parca CPU usage a lot lately.

**Comment by javierhonduco** [comment]
Was running for 30 minutes. I think the number of samples might be too low, but I am not sure. Might be that it's not spending that much time running on the CPU

**Comment by javierhonduco** [comment]
Closed by https://github.com/parca-dev/parca-agent/pull/641
