### ISSUE TITLE
optimization: Reduce the amount of memory the Agent uses

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#644]
We need to recheck what we cache. And the lifecycle of the cached items. 

I will attach profiles from our demo environment to this issue.

**Comment by javierhonduco** [comment]
Should we close this issue? It's based on pretty old profiles, and in general, we should always strive to keep the memory footprint of the agent as low as possible. We can open issues for specific issues that we spot that deserve fixing
