### ISSUE TITLE
Add process `comm` as label

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#652]
Now that we're doing whole system profiling with Parca Agent I think it would be useful to attach the processes `comm` as a label. By that I mean the content of `/proc/<PID>/comm`. I think for any environment that does not have established metadata (like Kubernetes) using the binary name of a process is a pretty good fallback.

**Comment by javierhonduco** [comment]
For more context, @kakkoyun added the executable name in https://github.com/parca-dev/parca-agent/pull/695. This is fetched by following [the symlink pointed by `/proc/<pid>/exe`](https://github.com/keybase/go-ps/blob/91aafc93ba19d1988cff338c1929d35b6c6f5b50/process_unix.go#L49). `comm` can be different to the process' executable, as it can be modified by the process. It's typically changed to set the name on a per-thread basis ([`proc(5)` manpage](https://man7.org/linux/man-pages/man5/proc.5.html))
