### ISSUE TITLE
Only log about debuginfo collection if it's turned off

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#660]
By default debuginfo collection is on and that's good, but it can be confusing to users that it is being logged about.

```
level=info ts=2022-08-02T19:28:49.497612717Z caller=main.go:163 msg="debug information collection is enabled"
```

I think we should only log about this when we turn it off as that's the situation we want to inform about.

**Comment by Namanl2001** [comment]
This issue has already been resolved [here](https://github.com/parca-dev/parca-agent/blob/HEAD/cmd/parca-agent/main.go#L651-L657)

**Comment by brancz** [comment]
Thanks for catching that!
