### ISSUE TITLE
Customizing labeling

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca-agent#7]
We currently apply certain non-customizable labeling of data, but that may not be identical to how users label their other observability data. We should allow customizing target labels, in the Prometheus ecosystem, this is done via [relabel configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config), however, often relabeling is confusing especially to new-comers, so unless we conclude we need all of the functionality that relabeling provides, I'd be ok with investigating alternative paths as well.

**Comment by brancz** [comment]
I'm not convinced that's totally necessary. The whole point of this project is to always profile everything. I would prefer if we focused all our efforts on reducing resource usage as much as possible.

**Comment by maxbrunet** [comment]
Prometheus's [`relabel.Process(...)`](https://pkg.go.dev/github.com/prometheus/prometheus/model/relabel#Process) can be re-used, probably around this line or within the writer's `Write()` (I'll experiment)


https://github.com/parca-dev/parca-agent/blob/c869910ebe3ceb7e7f3d86062cf213031f2ab6a8/pkg/profiler/cpu/cpu.go#L272

And then, reflect changes in the UI as well.
