### ISSUE TITLE
symbolizer/kernel: Add a mechanism to refresh kallsym cache

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#712]
https://github.com/parca-dev/parca-agent/pull/708 and https://github.com/parca-dev/parca-agent/pull/711 Introduce a simple caching for the contents of `kallsym` file.

We need to add a mechanism to update/invalidate that cache. We add a file listener, or we can add an interval-based polling mechanism to update the in-memory cache of the symbols.

cc @javierhonduco

**Comment by javierhonduco** [comment]
We update the data we parse from kallsyms when we notice that the mapping are stale (mismatching hash) or when some timer times out:

https://github.com/parca-dev/parca-agent/blob/624148f5864ca95c2d89621316ac037c6fa3e39f/pkg/ksym/ksym.go#L109-L112

Do we need to refresh it in some other places/ways?

**Comment by kakkoyun** [comment]
> We update the data we parse from kallsyms when we notice that the mapping are stale (mismatching hash)

Do we do this now? (I might have missed that)

**Comment by javierhonduco** [comment]
Yes, the code snippet above is from the PR we just landed. Updated the link above with the revision on main

**Comment by kakkoyun** [comment]
@javierhonduco is this done?

**Comment by javierhonduco** [comment]
@kakkoyun yes, the original implementation reloads the kernel symbols from time to time, e.g. when the hash mismatches or when the timer times out.

Have you observed it behaving differently?

**Comment by kakkoyun** [comment]
Noop. I was just tiraging the issues! Thanks 🙏
