### ISSUE TITLE
Optimizations and enhancements for the .eh_frame based stack unwinding

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca-agent#749]
Let's use this to keep track of all the further optimization and enhancement ideas we wish to tackle once we are satisfied with the correctness of `.eh_frame` based unwinding.

- [ ] Support for the DWARF64 (this can be directly contributed to Delve)
- [ ] Caching of eh_frame parsing for dynamic libraries (we would need to adjust the offsets, but at least we won't have to parse them every single time. For the first iteration, it's fine to do this work over and over)
- [x] Reduce the table row size. Right now it's 4x u64 (PC, $rsp offset, $rbp offset, metadata) but we can probably get away with 2x u64 (layout tbd) if the verifier doesn't complain due to the potential increase in analysed program paths https://github.com/parca-dev/parca-agent/pull/978/commits/03495a09be453e06b81ddfca8df4c9a5a8eb8834

**Comment by v-thakkar** [comment]
eBPF Program:

- Different sizes for the program counter: We're currently using 64 bits universally. Instead we can have 3 different sizes: 8 bit, 16 bit and 32 bit. It might be useful to do this. (JFYI, CTF frame also does the same).

**Comment by javierhonduco** [comment]
Just saw this issue, I think that using different PC sizes will be tricky, to say the least, in BPF. But I'll be incredibly happy if you prove me wrong 😄

**Comment by v-thakkar** [comment]
I think it can be doable. But challenge accepted :sweat_smile: I'll give it a try next week.

**Comment by javierhonduco** [comment]
Sounds good – I would suggest holding this on once v2 (loosening of the kernel version, bigger tables) lands, as some implementations that might work on the v1 might not work on v2

**Comment by v-thakkar** [comment]
This is not related anymore as we're using other issues to track the stack unwinding-related work. Check #1286 , #874
