### ISSUE TITLE
perf-map not found from latest parca-agent version

### ISSUE THREAD

**Issue by Pryz** [parca-dev/parca-agent#750]
I wanted to test the debuginfo caching fix but after deploying the agent from the `main` branch I'm hitting the following error:
```
failed to resolve user JITed functions: perf-map not found
``` 

From https://github.com/parca-dev/parca-agent/blob/main/pkg/perf/perf.go#L141 looks like we are expecting a perf map file but I'm not sure where this file is supposed to come from. I don't see any `.map` file on the instances I'm operating.

Also looks like we are going to return perf-map not found error as well if the procfs status file doesn't exist which might be confusing during troubleshooting.

**Comment by maxbrunet** [comment]
The runtime needs to be configured to create it. Some examples can be found here: https://github.com/parca-dev/parca-demo.

E.g for NodeJS, it is the `--perf-basic-prof` flag.

**Comment by Pryz** [comment]
Was reading the code perf map are actually not going to be used on my setup since I'm mostly profiling Go binaries. So mostly a red herring. I think my issue is due to the target discovery instead.

**Comment by brancz** [comment]
What log level was this at? Either way, I think we should make it clear in the log line that most processes probably won't have perf-maps so it's safe to ignore. But we should also make sure this is a debug level log.

**Comment by maxbrunet** [comment]
I think the condition is simply inverted here, we do not want to return error if not found, but log it instead:

https://github.com/parca-dev/parca-agent/blob/4b7e8082dcc77bcaa0aa32373ff089df828114c2/pkg/symbol/symbol.go#L67-L72

I am fixing it in #755
