### ISSUE TITLE
metadata: Use go-systemd instead of depending on systemctl

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#760]
It is more resilient and generic rather than using `systemctl` https://github.com/coreos/go-systemd

**Comment by palash25** [comment]
@kakkoyun can i take this up if no one is working on this?

**Comment by maxbrunet** [comment]
Hey @palash25, thank you for your interest, I have some work ready, I'll open the PR on Monday. Sorry, I should have assigned myself

**Comment by kakkoyun** [comment]
@palash25 We have other good first issues. Please let us know if we can help you find things to start 🤗  Also feel free to join our bi-weekly office hours on Thursdays.

**Comment by palash25** [comment]
yeah no problem i would look for some other issues, thanks for the prompt response
