### ISSUE TITLE
.eh_frame: Table generation issues for parca-demo-cpp

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#772]
Opening this issue to keep track of table generation bugs/oddities. The two commands to output the tables are:

```
$ dist/eh-frame --executable internal/dwarf/frame/testdata/parca-demo-cpp
```

for our table generation, and:

```
$ readelf -wF internal/dwarf/frame/testdata/parca-demo-cpp
```

for `readelf`'s. From now on we will refer as "our" or "readelf' as them, respectively.

### CFA "exp" (401020..4010b0)

What's `exp`? 

**our**
```
=> Function start: 401020, Function end: 4010b0
	(found 3 rows)
	Loc: 401020 CFA: $rsp=16  	RBP: u
	Loc: 401026 CFA: $rsp=24  	RBP: u
	Loc: 401030 CFA: $rsp=24  	RBP: u
```

**readelf**
```
00000040 0000000000000024 00000044 FDE cie=00000000 pc=0000000000401020..00000000004010b0
   LOC           CFA      ra    
0000000000401020 rsp+16   c-8   
0000000000401026 rsp+24   c-8   
0000000000401030 exp      c-8   
```

### Missing instruction (4011f0..401243) https://github.com/parca-dev/parca-agent/pull/790
Note the missing instruction at `4011f4`

**our**
```
=> Function start: 4011f0, Function end: 401243
	(found 3 rows)
	Loc: 4011f0 CFA: $rsp=8   	RBP: u
	Loc: 4011f1 CFA: $rsp=16  	RBP: c-16 
	Loc: 401242 CFA: $rsp=8   	RBP: c-16 
```

**readelf**
```
00000088 000000000000001c 0000008c FDE cie=00000000 pc=00000000004011f0..0000000000401243
   LOC           CFA      rbp   ra    
00000000004011f0 rsp+8    u     c-8   
00000000004011f1 rsp+16   c-16  c-8   
00000000004011f4 rbp+16   c-16  c-8   
0000000000401242 rsp+8    c-16  c-8   
```

cc @v-thakkar @kakkoyun

**Comment by v-thakkar** [comment]
While using `dwarfdump` for checking some tables, I realized that it prints little more information than readelf for the CFA "exp" in the case of cpp-binary. So putting that here as I think it'll be helpful to narrow down the bug. It's related to DW_EXPR_VAL_EXPRESSION.

Command:  **dwarfdump --print-eh-frame -F parca-demo-cpp**

```
fde:
<    0><0x00401020:0x004010b0><><cie offset 0x00000044::cie index     0><fde offset 0x00000040 length: 0x00000024>
       <eh aug data len 0x0>
        0x00401020: <off cfa=16(r7) > <off r16=-8(cfa) > 
        0x00401026: <off cfa=24(r7) > <off r16=-8(cfa) > 
        0x00401030: <expr cfa=expr-block-len=11> <off r16=-8(cfa) > 
```
Code from dwarfdump that prints this: https://github.com/davea42/libdwarf-code/blob/master/src/bin/dwarfexample/frame1.c#L316

**Comment by kakkoyun** [comment]
```
dw_value_type determines the meaning of the other fields. It is one of DW_EXPR_OFFSET
(0), DW_EXPR_VAL_OFFSET(1), DW_EXPR_EXPRESSION(2) or
DW_EXPR_VAL_EXPRESSION(3).
```

```
If *value_type has the value DW_EXPR_VAL_EXPRESSION (1) then:
The calculation is exactly as for DW_EXPR_EXPRESSION (1) but the result of the DWARFexpression evaluation is the value of the table_column (not the address of the value). This
is a DWARF3/2 val_expression(E) rule
```

source: https://git.tobast.fr/m2-internship/compilation-bundle/raw/branch/master/dwarf-compilation.base/contrib/libdwarf/libdwarf/libdwarf2.1.pdf


We have the necessary instruction implementation for this (`DW_CFA_val_expression`). I'll check what instructions we can't match.
