### ISSUE TITLE
.eh_frame: Support sections other than `.eh_frame`

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#782]
Such as `.debug_frame`, `.zdebug_frame` and others that might have the unwind information. This is important as some binaries, such as Golang's, don't seem to have `.eh_frame`. Not sure yet what the difference might be but perhaps the non-cgo binaries don't produce these tables? 

```
[javierhonduco@fedora parca-agent]$ readelf -a ../parca/bin/parca  | grep eh_frame
[javierhonduco@fedora parca-agent]$ 
```

cc @kakkoyun @v-thakkar

**Comment by kakkoyun** [comment]
Yes, the vanilla Go binaries don't generate `.eh_frame` sections. and we have a plan to support the `.debug_frame` sections as a follow-up to the initial implementation. https://github.com/parca-dev/parca-agent/issues/617

`.zdebug_frame` is just the `gzip` compressed version of the section. Which is a legacy implementation that has recently dropped. https://github.com/golang/go/issues/50796

Go binaries include `.debug_frame` when DWARF information is requested. 

The difference between the formats is nicely explained in this blog post https://www.airs.com/blog/archives/460

Closing this on for the sake of existing issue  https://github.com/parca-dev/parca-agent/issues/617

**Comment by javierhonduco** [comment]
Could you clarify all the above (different sections that we want to support, etc) in that issue? Thanks!
