### ISSUE TITLE
.eh_frame: Check `libc.so.6` unwind tables

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#792]
I've spot-checked the tables generated for libc (`internal/dwarf/frame/testdata/libc.so.6`), but we need to invest more time in checking mismatches between our table generator and readelf's

**Comment by javierhonduco** [comment]
- https://github.com/parca-dev/parca-agent/pull/842 carries the right metadata when CFA is an expression
- https://github.com/parca-dev/parca-agent/pull/841 fixes our implementation save/restore opcodes, which was incorrect

**Comment by v-thakkar** [comment]
We've spot checked this with readelf output and we seem to be generating correct tables. Our generated table for libc can be found here: https://github.com/parca-dev/testdata/blob/main/tables/ours_libc_so_6.txt
