### ISSUE TITLE
discovery never forgets exited processes

### ISSUE THREAD

**Issue by maxbrunet** [parca-dev/parca-agent#806]
The discovery seems to never forgets a process even after it has exited. This is at least true for systemd. This could result in a slight memory leak on high churn nodes.

We want to keep the labels available until the current profiling loop finishes, beyond that there should be a clean up (mark for deletion with timestamp?).

The label cache keys also never expires (maybe use the [`WithExpireAfterWrite`](https://pkg.go.dev/github.com/goburrow/cache#WithExpireAfterWrite) option with 2x profiling interval):

https://github.com/parca-dev/parca-agent/blob/78837cd2d067b25c6b76c8e7dfc1b564784b6f98/pkg/discovery/discovery_manager.go#L129

**Comment by kakkoyun** [comment]
I swear I've put an expiring cache for this as you described :see_no_evil: Good catch!
Feel free to send the fix. Otherwise, I can handle it.
