### ISSUE TITLE
relabelling: cache the result of relabeling functions

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca-agent#890]
I think this can totally be a follow up, but relabel configs are pure functions meaning as long as relabel configs don’t change the produced labelset doesn’t change. Therefore for any given process we need to only relabel once and can from there cache the result.

_Originally posted by @brancz in https://github.com/parca-dev/parca-agent/pull/887#pullrequestreview-1137015174_

cc @maxbrunet

**Comment by maxbrunet** [comment]
Excellent idea! Invalidation would need to happen on config reloads and on updates from the service discovery
