### ISSUE TITLE
Problems with PID detection on k3s

### ISSUE THREAD

**Issue by paulfantom** [parca-dev/parca-agent#90]
I got multiple warnings like the one below when running parca-agent in k3s on ubuntu 20.04 server.

```
level=warn ts=2021-10-10T12:03:44.054726335Z caller=k8s.go:200 msg="skipping pod, cannot find pid" namespace=monitoring pod=prometheus-k8s-1 err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
```

`containerd.sock` on k3s is available in `/run/k3s/containerd/containerd.sock` so it might be good to add it to auto discovery.

An alternative approach could be to add a parameter to jsonnet library allowing passing socket configuration to the agent instead of patching arguments.

**Comment by kakkoyun** [comment]
There's already a flag to configure it. ref #48 However it's a good idea to automatically detect this.

**Comment by paulfantom** [comment]
Seems like `providerID` is not always set. `kubectl get no -ojson | jq -r '.items[0].spec.providerID'` gives empty string on my `v1.21.3+k3s1` cluster. However using following should always give info about containerd:
```shell
$ kubectl get no -ojson | jq -r '.items[0].status.nodeInfo.containerRuntimeVersion'
containerd://1.4.8-k3s1
```
And since the above is in `.Status` we do have a guarantee it is created by k3s binary, so it works on all k3s instances the same way.

Alternatively what about just blindly checking for the existence of `/run/k3s/containerd/containerd.sock`?

**Comment by brancz** [comment]
Closed by https://github.com/parca-dev/parca-agent/pull/210
