### ISSUE TITLE
ci: e2e tests not working on PR from forks

### ISSUE THREAD

**Issue by maxbrunet** [parca-dev/parca-agent#934]
`secrets` and ghcr.io are not available to forks.

https://github.com/parca-dev/parca-agent/blob/4ab2341857de53c935191775a9bf8a8214b00ba8/.github/workflows/container.yml#L187-L209

e2e tests should use a local registry instead. It should be possible to export/import the built image and pass it between steps with the upload/download actions.

**Comment by kakkoyun** [comment]
There are two ways to fix it either using a local registry with https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md or exporting image as tar and uploading it as artifact https://stackoverflow.com/a/65369271/1113525

The downside of the first object is, it should be within the job, you can't expose services to other jobs. And there's the challenge of accessing that image from minikube. The latter approach could be easier to tackle.

**Comment by maxbrunet** [comment]
> There are two ways to fix it either using a local registry with [docker/build-push-action@`master`/docs/advanced/local-registry.md](https://github.com/docker/build-push-action/blob/master/docs/advanced/local-registry.md?rgh-link-date=2022-11-02T14%3A36%3A01Z) or to export image as tar and uploading it as an artifact [stackoverflow.com/a/65369271/1113525](https://stackoverflow.com/a/65369271/1113525)

My suggestion was to combine both. With the Minikube's `none`, importing the image into Docker should be enough (I guess it is enough in any case as we could use `minikube docker-env`)
