### ISSUE TITLE
ci: e2e tests are flaky

### ISSUE THREAD

**Issue by Sylfrena** [parca-dev/parca-agent#947]
e2e tests were recently merged in #478 but the checks have been failing with flaky
behaviour due to various causes. This is a parent issue to track all the bugs and fixes to
stabilise the checks.

### Issues

- #934
- #945
- #987 

### PRs

- #923
- #962
- #1000
- #1061
- #1090

**Comment by kakkoyun** [comment]
All issues seem to be resolved. Is it safe to close this @Sylfrena?

**Comment by Sylfrena** [comment]
@kakkoyun totally forgot this was still open! Closing it, thanks for the reminder :D
