### ISSUE TITLE
Reduce ELF `Open` calls

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#964]
## Background

Currently, we are spending ~10% of the Agent's CPU cycles opening ELF files. We need to do this for our profiler to work, for example, the `build_id` is stored in an ELF section, but the current APIs result in excessive calls to `Open()` as the flamegraph below shows, as they mostly accept a string with the path to the elf file rather than an `*elf.File`.

## Potential impact 
While the savings I think this would get us are not very big (perhaps ~3%) I think that the APIs to deal with ELF files would be clearer. Something that we should measure once these changes land is how memory allocations and system calls are affected, as they should be reduced, too.

## CPU (cycles) profile
[link to the profile](https://demo.parca.dev/?currentProfileView=icicle&expression_a=parca_agent_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Bapp_kubernetes_io_name%3D%22parca-agent%22%7D&from_a=1666850084029&to_a=1666853684029&merge_a=true&time_selection_a=relative:hour|1)
<img width="736" alt="image" src="https://user-images.githubusercontent.com/959128/198212562-3df94aa3-c62a-4830-acce-78f2f868b380.png">

Each of the highlighter frames on the left is ~3% of the total Agent CPU. The smaller ones on the right, are around 0.3% CPU each

**Comment by marselester** [comment]
Hi! This PR partially reduces number of `elf.Open()` calls https://github.com/parca-dev/parca-agent/pull/1022.
