### ISSUE TITLE
Stack quality: kernel stack is not always in the right merged stack

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca-agent#979]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/959128/199471258-f3a18358-67e8-4cde-b1bd-30fe74f08a15.png">

**Comment by javierhonduco** [comment]
I've also seen this, which might be an instance of the same problem

<img width="300" alt="image" src="https://user-images.githubusercontent.com/959128/202730910-44321a75-28fe-4553-889a-1a42ab5f324c.png">

**Comment by brancz** [comment]
`0x0` addresses are something that the Parca server does. It throws away the address when the address does not correspond to any range of any available mapping.
